// Chapter 3-8 content data to be merged into DEFAULT_DATA
const CHAPTERS_3_TO_8 = [
// ============================== CHAPTER 3: FORCE AND PRESSURE ==============================
// NOTES
{id:"c3n1",topicId:"ch3-force",type:"note",subtopic:"Definition of Force",content:'FORCE is the cause which changes the state of a body (rest or motion) or changes the size or shape of a body.',explanation:'Force acts as a push or a pull that can make things move or stop. It can also stretch or squash an object.',teacherTip:'Think of force as the "Action Hero" that makes objects do something different.',examTip:'Always mention that force can change both the "state of motion" and the "shape" of an object.'},
{id:"c3n2",topicId:"ch3-force",type:"note",subtopic:"Weight and Mass",content:'Weight of a body is the force with which it is attracted towards the centre of earth. W = mg. Mass does not change with location but weight does.',explanation:'Mass is the amount of matter inside you, which doesn\'t change on the moon. Since the moon pulls less, you weigh less there even though mass is the same.',teacherTip:'Mass stays the same everywhere, but weight is a "moody" force that changes with gravity.',examTip:'Remember the formula W = m × g where m is mass and g is gravity.'},
{id:"c3n3",topicId:"ch3-force",type:"note",subtopic:"Units of Force",content:'S.I. unit of force is Newton (N). 1 Newton is the force which when acting on a body of mass 1 kg produces a speed of 1 m/s. 1 kgf = 9.8 N ≈ 10 N.',explanation:'One Newton is roughly the weight of a small apple. It links force directly to mass and acceleration.',teacherTip:'Multiply kgf by 10 to get approximate Newtons.',examTip:'Always use capital "N" when writing the unit symbol.'},
{id:"c3n4",topicId:"ch3-force",type:"note",subtopic:"Rigid and Non-Rigid Bodies",content:'RIGID body: Force causes only motion (no change in shape). NON-RIGID body: Force causes both motion AND change in size/shape.',explanation:'A rigid body is like a brick that doesn\'t bend. A non-rigid body is like a sponge that deforms when squeezed.',teacherTip:'Rigid = "Super Strong" stays in shape. Non-rigid = "Flexible" like playdough.',examTip:'For non-rigid bodies, force causes both "motion" and "deformation".'},
{id:"c3n5",topicId:"ch3-force",type:"note",subtopic:"Turning Effect / Moment of Force",content:'TURNING EFFECT (Moment of Force) = Force × perpendicular distance from pivot. S.I. unit = N m (Newton meter).',explanation:'This is the effect when you push a door and it swings on its hinges. The further from the hinge you push, the easier it is to turn.',teacherTip:'Torque = How hard × How far.',examTip:'Always check that the distance is "perpendicular" (at 90°) to the force.'},
{id:"c3n6",topicId:"ch3-force",type:"note",subtopic:"Thrust and Pressure",content:'THRUST: Force acting normally (perpendicularly) on a surface. PRESSURE = Thrust/Area = F/A. S.I. unit is pascal (Pa) or N m⁻².',explanation:'Pressure tells us how spread out a force is. A sharp needle has high pressure because all force is at one tiny point.',teacherTip:'Pressure is like "Force\'s concentration".',examTip:'Mention both N m⁻² and Pascal (Pa) as units of pressure.'},
{id:"c3n7",topicId:"ch3-force",type:"note",subtopic:"Atmospheric Pressure",content:'ATMOSPHERIC PRESSURE: Pressure exerted by air around us. 1 atm = 76 cm of Hg = 1.013 × 10⁵ Pa.',explanation:'This is the heavy weight of air above us pressing down on everything. We don\'t feel it because our body pushes back.',teacherTip:'You are carrying the weight of a small car on your head in air pressure!',examTip:'Memorize 1.013 × 10⁵ Pa for standard atmospheric pressure.'},
{id:"c3n8",topicId:"ch3-force",type:"note",subtopic:"Liquid Pressure",content:'Liquid Pressure = h × d × g. Depends on: (i) Height of liquid column (ii) Density of liquid (iii) Gravitational constant. Liquid exerts pressure in ALL directions.',explanation:'The deeper you dive, the more water above you presses down. Mercury creates more pressure than water because it\'s denser.',teacherTip:'Deep = High Pressure. Thick liquid = High Pressure.',examTip:'Remember P = h × d × g where h is depth, d is density, g is gravity.'},
// TRUE/FALSE
{id:"c3tf1",topicId:"ch3-force",type:"true_false",subtopic:"Objective Questions",question:"The S.I. unit of force is kgf.",correctAnswer:"false",answer:"False. The S.I. unit of force is Newton (N).",teacherTip:'S.I. units are the "Science International" standard.',examTip:'kgf is a gravitational unit, not S.I.'},
{id:"c3tf2",topicId:"ch3-force",type:"true_false",subtopic:"Objective Questions",question:"A force always produces both linear and turning motions.",correctAnswer:"false",answer:"False. A force produces turning motion only if the object is pivoted. Free objects get linear motion only.",teacherTip:'A push can make a ball roll straight OR make a door swing, but usually not both.',examTip:'Look for "always" in T/F questions — it often signals false.'},
{id:"c3tf3",topicId:"ch3-force",type:"true_false",subtopic:"Objective Questions",question:"Moment of force = force × perpendicular distance from the pivoted point.",correctAnswer:"true",answer:"True. Both the strength of force and its distance from pivot determine the turning effect.",teacherTip:'This is why it\'s easier to open a door by pushing near the handle than near the hinges.',examTip:'Include "perpendicular" in your definition.'},
{id:"c3tf4",topicId:"ch3-force",type:"true_false",subtopic:"Objective Questions",question:"Less force is needed when applied at a farther distance from the pivoted point.",correctAnswer:"true",answer:"True. Increasing distance increases leverage, creating more turning power with less effort.",teacherTip:'Distance is your friend when you need to turn something heavy.',examTip:'This is why spanners have long handles.'},
{id:"c3tf5",topicId:"ch3-force",type:"true_false",subtopic:"Objective Questions",question:"For a given thrust, pressure is more on a surface of large area.",correctAnswer:"false",answer:"False. For a given thrust, pressure is LESS on a large area. P = F/A — larger A means smaller P.",teacherTip:'Big area = "Comfortable" pressure. Small area = "Stinging" pressure.',examTip:'Pressure is inversely proportional to Area.'},
{id:"c3tf6",topicId:"ch3-force",type:"true_false",subtopic:"Objective Questions",question:"The S.I. unit of pressure is pascal.",correctAnswer:"true",answer:"True. 1 Pascal = 1 N/m². Named after Blaise Pascal.",teacherTip:'Pascal is the "Main Name" for pressure units.',examTip:'Be prepared to define 1 Pascal as 1 N/m².'},
{id:"c3tf7",topicId:"ch3-force",type:"true_false",subtopic:"Objective Questions",question:"A liquid exerts pressure in all directions.",correctAnswer:"true",answer:"True. Unlike solids which only push down, fluids push against anything they contact. Pressure increases with depth.",teacherTip:'Think of being underwater — water presses on your ears from every side.',examTip:'This is a fundamental property of fluids.'},
{id:"c3tf8",topicId:"ch3-force",type:"true_false",subtopic:"Objective Questions",question:"Higher we go, greater is the air pressure.",correctAnswer:"false",answer:"False. Air pressure DECREASES as we go higher because the atmosphere becomes thinner.",teacherTip:'Like a pile of blankets — the higher you are, the fewer blankets on top.',examTip:'Atmospheric pressure and altitude have an inverse relationship.'},
// FILL IN BLANKS
{id:"c3fb1",topicId:"ch3-force",type:"fill_blank",subtopic:"Objective Questions",question:"1 kgf = ______ N (nearly).",blankAnswer:"10",answer:"1 kgf = 10 N (nearly). Exact value is 9.8 N.",teacherTip:'"kgf" stands for kilogram-force, roughly ten Newtons.',examTip:'Use 10 N only when the question says "nearly" or "approximately".'},
{id:"c3fb2",topicId:"ch3-force",type:"fill_blank",subtopic:"Objective Questions",question:"Moment of force = ______ × distance from the point of turning.",blankAnswer:"force",answer:"Moment of force = force × distance from the point of turning.",teacherTip:'This is why it\'s easier to open a heavy gate by pushing at the edge.',examTip:'Always ensure the distance is measured in metres.'},
{id:"c3fb3",topicId:"ch3-force",type:"fill_blank",subtopic:"Objective Questions",question:"In a door, handle is provided ______ from the hinges.",blankAnswer:"farthest",answer:"Handle is placed farthest from the hinges to maximize turning effect with minimum force.",teacherTip:'Maximum distance = minimum effort for turning.',examTip:'Use "lever arm" or "perpendicular distance" to explain this design.'},
{id:"c3fb4",topicId:"ch3-force",type:"fill_blank",subtopic:"Objective Questions",question:"The unit of pressure is ______.",blankAnswer:"pascal",answer:"The unit of pressure is pascal (Pa).",teacherTip:'1 Pa is a very small amount of pressure.',examTip:'Capitalize "Pascal" but use lowercase "p" for symbol "Pa".'},
{id:"c3fb5",topicId:"ch3-force",type:"fill_blank",subtopic:"Objective Questions",question:"Pressure in a liquid ______ with the depth.",blankAnswer:"increases",answer:"Pressure in a liquid increases with the depth.",teacherTip:'Like a human pyramid — the person at the bottom feels the most pressure.',examTip:'Liquid pressure depends on depth (h) and density (d).'},
// MATCH
{id:"c3m1",topicId:"ch3-force",type:"match",subtopic:"Objective Questions",question:"Match Column A with Column B",pairs:[{left:"Camel",right:"broad feet"},{left:"Truck",right:"six or eight tyres"},{left:"Knife",right:"sharp cutting edge"},{left:"Thrust",right:"N (Newton)"},{left:"Moment of force",right:"N m"},{left:"Atmospheric pressure",right:"atm"}],answer:"Camel→broad feet, Truck→six or eight tyres, Knife→sharp cutting edge, Thrust→N, Moment of force→N m, Atmospheric pressure→atm",teacherTip:'Match biological/structural features to their scientific purpose.',examTip:'Write full correct pairs clearly.'},
// MCQs
{id:"c3mcq1",topicId:"ch3-force",type:"mcq",subtopic:"Objective Questions",question:"S.I. unit of moment of force is:",options:["N","N m⁻²","kgf","N m"],correctOption:3,answer:"N m. Since moment = Force (N) × Distance (m), the unit is Newton-meter.",teacherTip:'Moment = Force × Distance, so Unit = Newton × Meter.',examTip:'Do not confuse N m with N/m.'},
{id:"c3mcq2",topicId:"ch3-force",type:"mcq",subtopic:"Objective Questions",question:"The unit of pressure is:",options:["N","kgf","N m⁻²","N m"],correctOption:2,answer:"N m⁻² (or pascal). Pressure = Force / Area.",teacherTip:'The ⁻² exponent means "per square meter".',examTip:'N m⁻² and Pa are identical.'},
{id:"c3mcq3",topicId:"ch3-force",type:"mcq",subtopic:"Objective Questions",question:"The pressure and thrust are related as:",options:["Pressure = Thrust × Area","Thrust = Pressure / Area","Pressure = Thrust / Area","Pressure = Area / Thrust"],correctOption:2,answer:"Pressure = Thrust / Area. The fundamental formula of the chapter.",teacherTip:'Pressure is the "Average Push" on every tiny bit of surface.',examTip:'Rearrange to Thrust = Pressure × Area as well.'},
{id:"c3mcq4",topicId:"ch3-force",type:"mcq",subtopic:"Objective Questions",question:"The atmospheric pressure at sea level is nearly:",options:["10 Pa","100,000 Pa","1000 Pa","10,000 Pa"],correctOption:1,answer:"100,000 Pa (10⁵ Pa). This is the standard measurement for sea-level air pressure.",teacherTip:'10⁵ is a shorter way to write 100,000.',examTip:'Be ready to see this as 10⁵ Pa or 100,000 Pa — they\'re the same.'},
// SHORT ANSWER
{id:"c3sa1",topicId:"ch3-force",type:"short_answer",subtopic:"Short/Long Answer",question:"Define force. State its S.I. unit.",answer:'Force is a physical cause that changes or may tend to change the state of rest or the state of motion of an object. The S.I. unit of force is Newton (N).',teacherTip:'Force = Push or Pull.',examTip:'Mention "tend to change" to include forces that don\'t result in actual movement.'},
{id:"c3sa2",topicId:"ch3-force",type:"short_answer",subtopic:"Short/Long Answer",question:"State two effects of a force when applied on a body.",answer:'(i) It can change the state of body — stop a moving object or move a stationary object.\n(ii) It can change the shape and size of an object.',teacherTip:'Think "Motion" and "Makeover" (shape change).',examTip:'Use clear examples like "stopping a ball" to illustrate.'},
{id:"c3sa3",topicId:"ch3-force",type:"short_answer",subtopic:"Short/Long Answer",question:"Define the term moment of force. State its S.I. unit and two factors affecting it.",answer:'Moment of force is the turning effect of force acting on a body about an axis.\nS.I. unit: N m (Newton meter)\nFactors: (i) Magnitude of force applied (ii) Perpendicular distance from axis of rotation.',teacherTip:'Moment of force is the scientific name for "Turning Power".',examTip:'Always relate to an "axis" or "pivot point".'},
{id:"c3sa4",topicId:"ch3-force",type:"short_answer",subtopic:"Short/Long Answer",question:"Define pressure. State its S.I. unit and the formula.",answer:'Pressure is the thrust (force) acting perpendicularly per unit area of a surface.\nP = F/A (Thrust/Area)\nS.I. unit: Pascal (Pa) = N m⁻²',teacherTip:'Pressure is like "Force Density" on a surface.',examTip:'Include both N m⁻² and Pascal (Pa) as equivalent units.'},
{id:"c3sa5",topicId:"ch3-force",type:"short_answer",subtopic:"Short/Long Answer",question:"State two factors affecting pressure. Give examples.",answer:'(i) Area: Greater area = lesser pressure (e.g., camels have broad feet to walk on sand)\n(ii) Magnitude of thrust: Greater thrust = greater pressure (e.g., pressing harder with a nail)\nAlso: Sharp knife cuts easily because small area gives high pressure.',teacherTip:'Sharp things = Small Area = High Pressure.',examTip:'Use "inversely proportional" for area and "directly proportional" for thrust.'},
{id:"c3sa6",topicId:"ch3-force",type:"short_answer",subtopic:"Short/Long Answer",question:"State three factors affecting liquid pressure. Give the formula.",answer:'Liquid Pressure P = h × d × g\nFactors:\n(i) Height of liquid column (h) — increases with depth\n(ii) Density of liquid (d) — increases with density\n(iii) Gravitational constant (g)',teacherTip:'Deep = High Pressure. Thick liquid = High Pressure.',examTip:'Remember P = h × d × g.'},
{id:"c3sa7",topicId:"ch3-force",type:"short_answer",subtopic:"Short/Long Answer",question:"Why does nose bleeding occur at high altitudes?",answer:'At high altitudes, atmospheric pressure decreases. The blood pressure inside our body becomes greater than external atmospheric pressure. This pressure difference causes thin blood vessels in the nose to burst, resulting in nose bleeding.',teacherTip:'It\'s like a balloon popping because the air outside got too thin.',examTip:'Explain that "internal blood pressure" exceeds "external atmospheric pressure".'},

// ============================== CHAPTER 4: ENERGY ==============================
// NOTES
{id:"c4n1",topicId:"ch4-energy",type:"note",subtopic:"Work - Definition & Formula",content:'WORK is done when force applied on a body causes displacement in the direction of force. W = F × d. S.I. unit is Joule (J). 1 J = 1 N × 1 m.',explanation:'Work is the transfer of energy through motion. No movement = no work (e.g., pushing a wall).',teacherTip:'No movement means no work, no matter how much effort you put in!',examTip:'Always explain that displacement is zero in cases like pushing a wall.'},
{id:"c4n2",topicId:"ch4-energy",type:"note",subtopic:"Conditions for Zero Work",content:'No work is done when: (i) No displacement (S = 0), e.g., pushing a wall. (ii) Displacement is perpendicular to force (θ = 90°), e.g., coolie walking with box on head.',explanation:'A coolie with a box on his head walking does no work against gravity — force is vertical, motion is horizontal.',teacherTip:'Pushing "Up" while moving "Forward" = zero work done on the load.',examTip:'Mention that the angle between force and displacement is 90°.'},
{id:"c4n3",topicId:"ch4-energy",type:"note",subtopic:"Energy - Definition",content:'ENERGY is the capacity of doing work. S.I. unit = Joule (J). Same unit as work.',explanation:'Energy is like a "bank account" that allows objects to perform actions. Because work and energy are the same thing in different forms, they share units.',teacherTip:'Think of energy as the "fuel" needed to perform work.',examTip:'Defining energy as "capacity to do work" is the most accurate definition.'},
{id:"c4n4",topicId:"ch4-energy",type:"note",subtopic:"Mechanical Energy: PE and KE",content:'MECHANICAL ENERGY = Potential Energy + Kinetic Energy.\nPOTENTIAL ENERGY (P.E.) = mgh — energy due to position/height.\nKINETIC ENERGY (K.E.) = ½mv² — energy due to motion.',explanation:'PE is stored energy (a book on a shelf). KE is movement energy (a rolling ball). They can convert into each other.',teacherTip:'PE and KE are like two sides of the same mechanical coin.',examTip:'When a body falls: PE decreases, KE increases. Total remains constant.'},
{id:"c4n5",topicId:"ch4-energy",type:"note",subtopic:"Power",content:'POWER is the rate of doing work. P = W/t. S.I. unit = Watt (W) = J/s. 1 H.P. = 746 W.',explanation:'Power measures how fast work is being done. A more powerful motor lifts weight faster.',teacherTip:'Power is just "Work with a stopwatch".',examTip:'Use P = W/t when given "Work" and "Seconds".'},
// TRUE/FALSE
{id:"c4tf1",topicId:"ch4-energy",type:"true_false",subtopic:"Objective Questions",question:"A coolie does no work against the force of gravity while carrying luggage on a road.",correctAnswer:"true",answer:"True. The motion is horizontal but gravity is vertical — angle is 90° so work against gravity is zero.",teacherTip:'Work requires force and motion to be in the same line!',examTip:'Specify angle is 90° between force and motion.'},
{id:"c4tf2",topicId:"ch4-energy",type:"true_false",subtopic:"Objective Questions",question:"The energy stored in water of a dam is the kinetic energy.",correctAnswer:"false",answer:"False. Water in a dam is at a great height — it has gravitational POTENTIAL energy.",teacherTip:'Static things at a height have "Potential," not Kinetic energy.',examTip:'If water is "stored" or "still," the answer is Potential Energy.'},
{id:"c4tf3",topicId:"ch4-energy",type:"true_false",subtopic:"Objective Questions",question:"Work done by a boy depends on the time in which he does work.",correctAnswer:"false",answer:"False. Work depends only on force and distance, not time. Time is used to calculate Power.",teacherTip:'Work doesn\'t care about the clock; Power does!',examTip:'Do not include "time" in your formula for Work.'},
{id:"c4tf4",topicId:"ch4-energy",type:"true_false",subtopic:"Objective Questions",question:"Power spent by a body depends on the time for which it does work.",correctAnswer:"true",answer:"True. Power = Work/Time. Same work in less time = more power.",teacherTip:'Power is "Speedy Work".',examTip:'Power is inversely proportional to time for a given amount of work.'},
// FILL IN BLANKS
{id:"c4fb1",topicId:"ch4-energy",type:"fill_blank",subtopic:"Objective Questions",question:"Work done = Force × ______.",blankAnswer:"distance",answer:"Work done = Force × distance moved in direction of force.",teacherTip:'Direction matters! Push and move must be in the same line.',examTip:'Memorize W = F × d as your primary work formula.'},
{id:"c4fb2",topicId:"ch4-energy",type:"fill_blank",subtopic:"Objective Questions",question:"The S.I. unit of energy is ______.",blankAnswer:"joule",answer:"The S.I. unit of energy is joule (J).",teacherTip:'Joule is the "Global Currency" for energy.',examTip:'Joule is used for both Work and Energy.'},
{id:"c4fb3",topicId:"ch4-energy",type:"fill_blank",subtopic:"Objective Questions",question:"Kinetic energy = ½ × mass × ______.",blankAnswer:"(speed)²",answer:"Kinetic energy = ½ × mass × (speed)². Doubling speed quadruples KE!",teacherTip:'Speed has a much bigger effect on KE than mass does.',examTip:'Don\'t forget "½" and "squared" in the KE formula.'},
{id:"c4fb4",topicId:"ch4-energy",type:"fill_blank",subtopic:"Objective Questions",question:"1 H.P. = ______ W.",blankAnswer:"746",answer:"1 H.P. = 746 W.",teacherTip:'746 is the "Magic Number" to convert H.P. to Watts.',examTip:'Memorize this exact value for unit conversion questions.'},
// MATCH
{id:"c4m1",topicId:"ch4-energy",type:"match",subtopic:"Objective Questions",question:"Match Column A with Column B",pairs:[{left:"A stone at a height",right:"potential energy"},{left:"A moving ball",right:"kinetic energy"},{left:"Energy",right:"joule"},{left:"Power",right:"work done in 1 s"},{left:"watt",right:"power"}],answer:"Stone at height→PE, Moving ball→KE, Energy→joule, Power→work done in 1s, watt→power",teacherTip:'Match objects to their "Energy Type" and units to their "Quantities".',examTip:'Draw clean straight lines for matching.'},
// MCQs
{id:"c4mcq1",topicId:"ch4-energy",type:"mcq",subtopic:"Objective Questions",question:"The S.I. unit of work is:",options:["second","metre","joule","newton"],correctOption:2,answer:"Joule. Work and energy always use the Joule as their standard unit.",teacherTip:'Joule = Work.',examTip:'Be careful not to pick Newton (force) by mistake.'},
{id:"c4mcq2",topicId:"ch4-energy",type:"mcq",subtopic:"Objective Questions",question:"No work is done by a force if the body:",options:["moves in direction of force","does not move","moves in opposite direction","none of these"],correctOption:1,answer:"Does not move. If displacement = 0, then F × d = 0.",teacherTip:'"Static" objects have zero work done on them.',examTip:'"No work" usually points to "no displacement".'},
{id:"c4mcq3",topicId:"ch4-energy",type:"mcq",subtopic:"Objective Questions",question:"When a boy doubles his speed, his kinetic energy becomes:",options:["half","double","four times","no change"],correctOption:2,answer:"Four times. KE = ½mv². Doubling v gives (2v)² = 4v², so KE becomes 4 times.",teacherTip:'Double speed = Quadruple energy (2 × 2 = 4).',examTip:'Use the v² part of the formula to explain.'},
{id:"c4mcq4",topicId:"ch4-energy",type:"mcq",subtopic:"Objective Questions",question:"A boy lifts luggage from height 2 m to 4 m. The potential energy will become:",options:["half","double","one-third","one-fourth"],correctOption:1,answer:"Double. PE is directly proportional to height. 4m is twice 2m.",teacherTip:'Double height = Double PE.',examTip:'Heights and PE follow the same ratio if mass is constant.'},
// SHORT ANSWER
{id:"c4sa1",topicId:"ch4-energy",type:"short_answer",subtopic:"Short/Long Answer",question:"Define work. State two conditions when no work is done.",answer:'Work is done when a force applied on a body causes displacement in the direction of force. W = F × d.\n\nNo work is done when:\n(i) Displacement S = 0 (e.g., pushing a wall)\n(ii) Displacement is perpendicular to force, θ = 90° (e.g., coolie walking with load on head)',teacherTip:'Zero move OR Zero angle = Zero Work.',examTip:'List both conditions separately for full credit.'},
{id:"c4sa2",topicId:"ch4-energy",type:"short_answer",subtopic:"Short/Long Answer",question:"Define energy. What are the two kinds of mechanical energy?",answer:'ENERGY: Capacity of doing work. S.I. unit = Joule (J).\n\nTwo kinds of mechanical energy:\n(i) Potential Energy (PE) — energy due to position or shape\n(ii) Kinetic Energy (KE) — energy due to motion\n\nMechanical Energy = PE + KE',teacherTip:'PE = Place; KE = Kick (motion).',examTip:'Mention both PE and KE as components of mechanical energy.'},
{id:"c4sa3",topicId:"ch4-energy",type:"short_answer",subtopic:"Short/Long Answer",question:"Write expressions for PE and KE, explaining symbols used.",answer:'PE = mgh where m = mass, g = acceleration due to gravity, h = height above ground.\n\nKE = ½mv² where m = mass, v = speed/velocity.\n\nPE depends on mass and height. KE depends on mass and velocity (v² makes speed very important).',teacherTip:'P.E. likes heavy things and high places. K.E. loves speed.',examTip:'Label each symbol clearly to get full marks.'},
{id:"c4sa4",topicId:"ch4-energy",type:"short_answer",subtopic:"Short/Long Answer",question:"Define power. State its S.I. unit. What is 1 H.P.?",answer:'Power is the rate of doing work. P = W/t = F × d/t.\nS.I. unit: Watt (W) = J/s.\n1 H.P. (Horse Power) = 746 W.',teacherTip:'1 Watt = 1 Joule per second.',examTip:'Use P = W/t when given "Work" and "Seconds".'},
{id:"c4sa5",topicId:"ch4-energy",type:"short_answer",subtopic:"Short/Long Answer",question:"Name the type of energy: (a) moving cricket ball (b) stone on building top (c) compressed spring (d) stretched rubber band (e) water flowing in river",answer:'(a) Moving cricket ball — Kinetic Energy (due to motion)\n(b) Stone on building top — Potential Energy (due to height)\n(c) Compressed spring — Potential Energy (due to changed shape)\n(d) Stretched rubber band — Potential Energy (due to elongated state)\n(e) Water flowing in river — Kinetic Energy (due to motion)',teacherTip:'Motion = Kinetic; Height/Stretching = Potential.',examTip:'Label the specific reason next to your answer.'},

// ============================== CHAPTER 5: LIGHT ENERGY ==============================
// NOTES
{id:"c5n1",topicId:"ch5-light",type:"note",subtopic:"Nature of Light",content:'Light is a form of energy that produces sensation of sight. Speed in vacuum/air = 3 × 10⁸ m/s. Speed decreases in denser media: water (2.25 × 10⁸), glass (2 × 10⁸). Light travels in straight lines.',explanation:'Light travels fastest in vacuum and slows down in denser materials like water and glass.',teacherTip:'As the material gets harder (Gas → Liquid → Solid), light gets slower.',examTip:'Memorize speed of light in air: 3 × 10⁸ m/s.'},
{id:"c5n2",topicId:"ch5-light",type:"note",subtopic:"Refraction of Light",content:'REFRACTION: Change in direction of light when passing from one transparent medium to another. Rarer to Denser → bends TOWARDS normal. Denser to Rarer → bends AWAY from normal.',explanation:'Light bends because it changes speed at the boundary between two media.',teacherTip:'Use mnemonic "DRA" — Denser to Rarer = Away from normal.',examTip:'Both media must be "transparent" for refraction to occur.'},
{id:"c5n3",topicId:"ch5-light",type:"note",subtopic:"Laws of Refraction (Snell\'s Law)",content:'(i) Incident ray, normal, and refracted ray all lie in the same plane.\n(ii) sin∠i / sin∠r = constant = Refractive Index (μ).\nR.I. = Speed in air / Speed in medium = Real depth / Apparent depth.',explanation:'The ratio of sines of angles is constant for any two media. Higher R.I. = slower light = denser medium.',teacherTip:'R.I. of water = 1.33, glass = 1.5.',examTip:'Use μ = sin i / sin r for calculations.'},
{id:"c5n4",topicId:"ch5-light",type:"note",subtopic:"Dispersion of Light",content:'DISPERSION: Splitting of white light into seven colours (VIBGYOR) by a prism. White light is a band of seven colours. In glass: violet is slowest, red is fastest.',explanation:'Each colour has different speed in glass, so they bend by different amounts and separate.',teacherTip:'Rainbows are a natural form of dispersion.',examTip:'Violet bends the most, Red bends the least.'},
{id:"c5n5",topicId:"ch5-light",type:"note",subtopic:"Spherical Mirrors",content:'CONCAVE mirror: converges light, forms real/virtual images. Used as shaving mirror.\nCONVEX mirror: diverges light, always forms virtual, erect, diminished image. Used as rear-view mirror.\nFocal length f = R/2 (R = radius of curvature).',explanation:'Concave mirrors focus light to a point. Convex mirrors spread light out giving a wider field of view.',teacherTip:'Concave = "cave in" bringing light to center. Convex = "bulge out" spreading light.',examTip:'f = R/2 is a key formula for mirror calculations.'},
// TRUE/FALSE
{id:"c5tf1",topicId:"ch5-light",type:"true_false",subtopic:"Objective Questions",question:"Water is optically denser than glass.",correctAnswer:"false",answer:"False. Glass (R.I. = 1.5) is optically denser than water (R.I. = 1.33). Light is slower in glass.",teacherTip:'Remember: Air (1.0), Water (1.33), Glass (1.5).',examTip:'Use "optical density" to describe how much a medium slows light.'},
{id:"c5tf2",topicId:"ch5-light",type:"true_false",subtopic:"Objective Questions",question:"A ray of light from glass to air bends towards the normal.",correctAnswer:"false",answer:"False. Glass to air = denser to rarer = bends AWAY from normal.",teacherTip:'Use mnemonic "DRA" — Denser to Rarer = Away.',examTip:'Draw the normal perpendicular to the surface.'},
{id:"c5tf3",topicId:"ch5-light",type:"true_false",subtopic:"Objective Questions",question:"The speed of light is more in glass than in water.",correctAnswer:"false",answer:"False. Glass is denser than water. Light in water = 2.25×10⁸, in glass = 2×10⁸ m/s. Slower in glass.",teacherTip:'Denser materials = "thicker traffic" for light.',examTip:'Speed is inversely proportional to refractive index.'},
{id:"c5tf4",topicId:"ch5-light",type:"true_false",subtopic:"Objective Questions",question:"The depth of a pond seen from above appears to be less.",correctAnswer:"true",answer:"True. Refraction makes light from the bottom bend away from normal as it enters air, making the bottom appear raised.",teacherTip:'This is called "Apparent Depth" — pools look shallower than they are.',examTip:'Use dotted line for virtual position of raised object.'},
{id:"c5tf5",topicId:"ch5-light",type:"true_false",subtopic:"Objective Questions",question:"A convex mirror is used as a shaving mirror.",correctAnswer:"false",answer:"False. CONCAVE mirrors are used as shaving mirrors because they form enlarged, erect images when held close to face.",teacherTip:'Shaving needs "zoom," so we use concave mirrors.',examTip:'Convex mirrors are used as rear-view mirrors.'},
{id:"c5tf6",topicId:"ch5-light",type:"true_false",subtopic:"Objective Questions",question:"A concave mirror converges light rays, but a convex mirror diverges them.",correctAnswer:"true",answer:"True. Concave mirrors reflect rays inward toward a focus. Convex mirrors reflect rays outward.",teacherTip:'Converge = Come together; Diverge = Drive apart.',examTip:'Use arrows to show direction of reflected rays in diagrams.'},
// FILL IN BLANKS
{id:"c5fb1",topicId:"ch5-light",type:"fill_blank",subtopic:"Objective Questions",question:"Water is optically ______ than air.",blankAnswer:"denser",answer:"Water is optically denser than air.",teacherTip:'Rarer = thinner; Denser = thicker.',examTip:'Write "optically denser" for physics accuracy.'},
{id:"c5fb2",topicId:"ch5-light",type:"fill_blank",subtopic:"Objective Questions",question:"When white light passes through a prism, it ______.",blankAnswer:"disperses",answer:"When white light passes through a prism, it disperses into seven colours (VIBGYOR).",teacherTip:'A prism is a "color separator."',examTip:'White light must fall obliquely for dispersion.'},
{id:"c5fb3",topicId:"ch5-light",type:"fill_blank",subtopic:"Objective Questions",question:"Radius of curvature of a spherical mirror is ______ times its focal length.",blankAnswer:"two",answer:"Radius of curvature = 2 × focal length. R = 2f.",teacherTip:'R = 2f. Use this to check your math!',examTip:'State units (cm) when giving values for R or f.'},
{id:"c5fb4",topicId:"ch5-light",type:"fill_blank",subtopic:"Objective Questions",question:"A ______ mirror always forms a virtual image.",blankAnswer:"convex",answer:"A convex mirror always forms a virtual, erect, diminished image.",teacherTip:'Convex = "always small and upright" mirror.',examTip:'Virtual images are always erect and diminished for convex mirrors.'},
// MCQs
{id:"c5mcq1",topicId:"ch5-light",type:"mcq",subtopic:"Objective Questions",question:"The speed of light in air or vacuum is:",options:["3 × 10⁸ m/s","2.25 × 10⁸ m/s","2 × 10⁸ m/s","3 × 10⁶ m/s"],correctOption:0,answer:"3 × 10⁸ m/s. This is a fundamental physical constant.",teacherTip:'That\'s 300,000 km every single second!',examTip:'Units must be m/s.'},
{id:"c5mcq2",topicId:"ch5-light",type:"mcq",subtopic:"Objective Questions",question:"The seven colours of sunlight in order are:",options:["VIBGYOR","ROYGBIV","BGYROVI","GYBRIOV"],correctOption:0,answer:"VIBGYOR — Violet, Indigo, Blue, Green, Yellow, Orange, Red.",teacherTip:'Use "Roy G. Biv" backwards.',examTip:'Violet bends most, Red bends least.'},
{id:"c5mcq3",topicId:"ch5-light",type:"mcq",subtopic:"Objective Questions",question:"If radius of curvature of a concave mirror is 20 cm, its focal length is:",options:["10 cm","20 cm","40 cm","5 cm"],correctOption:0,answer:"10 cm. f = R/2 = 20/2 = 10 cm.",teacherTip:'Radius is always the "big" number, focal length is the "small" number.',examTip:'Include the unit (cm) in your answer.'},
{id:"c5mcq4",topicId:"ch5-light",type:"mcq",subtopic:"Objective Questions",question:"A convex mirror is used:",options:["as a shaving mirror","in a torch","as a rear view mirror by a driver","to focus sunlight"],correctOption:2,answer:"As a rear view mirror. Convex mirrors give a wide field of view by shrinking images.",teacherTip:'"Objects in mirror are closer than they appear."',examTip:'Mention "wide field of view" as the reason.'},
// SHORT ANSWER
{id:"c5sa1",topicId:"ch5-light",type:"short_answer",subtopic:"Short/Long Answer",question:"State the speed of light in (a) air (b) water (c) glass.",answer:'(a) Air: 3 × 10⁸ m/s\n(b) Water: 2.25 × 10⁸ m/s\n(c) Glass: 2 × 10⁸ m/s\n\nLight slows down in denser media.',teacherTip:'As material gets denser, light gets slower.',examTip:'Use 10⁸ scientific notation.'},
{id:"c5sa2",topicId:"ch5-light",type:"short_answer",subtopic:"Short/Long Answer",question:"What is refraction of light? State the laws of refraction.",answer:'REFRACTION: Change in direction of path of light when it passes from one transparent medium to another.\n\nLaws of Refraction (Snell\'s Laws):\n(i) Incident ray, normal at point of incidence, and refracted ray all lie in the same plane.\n(ii) sin∠i / sin∠r = constant = Refractive Index (μ).',teacherTip:'Refraction = Bending at the border.',examTip:'Both media must be "transparent" for refraction.'},
{id:"c5sa3",topicId:"ch5-light",type:"short_answer",subtopic:"Short/Long Answer",question:"What is dispersion of light? Name the seven colours.",answer:'DISPERSION: The splitting of white light into its seven constituent colours when passed through a prism.\n\nSeven colours (VIBGYOR): Violet, Indigo, Blue, Green, Yellow, Orange, Red.\n\nCause: Different colours have different speeds in glass, so they separate on refraction.',teacherTip:'Rainbows are natural dispersion.',examTip:'Violet bends most (slowest in glass), Red bends least (fastest in glass).'},

// ============================== CHAPTER 6: HEAT TRANSFER ==============================
// NOTES
{id:"c6n1",topicId:"ch6-heat",type:"note",subtopic:"Heat Transfer Basics",content:'Heat is a form of energy. It flows from higher temperature to lower temperature body until both reach same temperature. When heated: (i) body expands (ii) temperature changes (iii) state changes.',explanation:'Heat energy makes molecules move faster, increasing kinetic energy. When cooling, KE decreases.',teacherTip:'Heat always flows from hot to cold, never the other way.',examTip:'Mention all three effects of heating for complete answer.'},
{id:"c6n2",topicId:"ch6-heat",type:"note",subtopic:"Change of State",content:'MELTING: Solid → Liquid at constant temperature. Melting Point of ice = 0°C.\nBOILING: Liquid → Gas at constant temperature. Boiling Point of water = 100°C.\nEVAPORATION: Liquid → Gas at ALL temperatures (surface phenomenon). Produces cooling.\nSUBLIMATION: Solid → Gas directly.',explanation:'Temperature remains constant during change of state. Heat is used to break molecular bonds.',teacherTip:'Evaporation = slow at surface. Boiling = fast throughout.',examTip:'Distinguish boiling (fixed temp) from evaporation (all temps).'},
{id:"c6n3",topicId:"ch6-heat",type:"note",subtopic:"Linear Expansion",content:'When a metal rod is heated, its length increases. Increase depends on: (i) original length (ii) rise in temperature (iii) material of rod.\nCoefficient of linear expansion α = (Lt - L₀)/(L₀ × T).\nα : β : γ = 1 : 2 : 3 (linear : superficial : cubical).',explanation:'Different materials expand at different rates. This is used in bimetallic strips for thermostats.',teacherTip:'Brass expands more than iron when heated by the same amount.',examTip:'Remember α : β : γ = 1 : 2 : 3.'},
{id:"c6n4",topicId:"ch6-heat",type:"note",subtopic:"Expansion Order",content:'Order of expansion: Gases > Liquids > Solids. Alcohol expands more than water. Iron expands less than copper.',explanation:'Gases have weakest intermolecular forces, so molecules move apart most easily when heated.',teacherTip:'Gases are the "expansion champions".',examTip:'State the order: Gas > Liquid > Solid expansion.'},
// TRUE/FALSE
{id:"c6tf1",topicId:"ch6-heat",type:"true_false",subtopic:"Objective Questions",question:"Evaporation is rapid on a wet day.",correctAnswer:"false",answer:"False. On a wet day, air is saturated with moisture — little room for more water to evaporate. High humidity slows evaporation.",teacherTip:'High humidity = crowded room where no one else can enter.',examTip:'Evaporation rate is inversely proportional to humidity.'},
{id:"c6tf2",topicId:"ch6-heat",type:"true_false",subtopic:"Objective Questions",question:"Evaporation takes place only from the surface of liquid.",correctAnswer:"true",answer:"True. Evaporation is a surface phenomenon — only molecules at the top escape into air.",teacherTip:'Like people leaving a stadium — only those near exits can leave first.',examTip:'Use "surface phenomenon" to describe evaporation.'},
{id:"c6tf3",topicId:"ch6-heat",type:"true_false",subtopic:"Objective Questions",question:"Temperature of a liquid rises during boiling.",correctAnswer:"false",answer:"False. Temperature remains CONSTANT during boiling. Heat is used to change state (latent heat), not raise temperature.",teacherTip:'During "change of state," the thermometer stays still.',examTip:'Mention "Latent Heat" to explain constant temperature.'},
{id:"c6tf4",topicId:"ch6-heat",type:"true_false",subtopic:"Objective Questions",question:"Solids expand the least and gases expand the most on being heated.",correctAnswer:"true",answer:"True. Gases have weakest intermolecular forces, allowing molecules to move far apart easily.",teacherTip:'Order: Gas > Liquid > Solid expansion.',examTip:'Mention "weak intermolecular forces" for gases.'},
{id:"c6tf5",topicId:"ch6-heat",type:"true_false",subtopic:"Objective Questions",question:"All solids expand by the same amount when heated to the same rise in temperature.",correctAnswer:"false",answer:"False. Different solids have different coefficients of expansion. Brass expands more than iron.",teacherTip:'Every material has its own "personality" of expansion.',examTip:'Expansion depends on "nature of the material."'},
// FILL IN BLANKS
{id:"c6fb1",topicId:"ch6-heat",type:"fill_blank",subtopic:"Objective Questions",question:"Boiling occurs at a ______ temperature.",blankAnswer:"fixed",answer:"Boiling occurs at a fixed temperature (e.g., water boils at 100°C).",teacherTip:'Boiling is like a scheduled appointment at a specific temperature.',examTip:'Distinguish boiling (fixed) from evaporation (any temperature).'},
{id:"c6fb2",topicId:"ch6-heat",type:"fill_blank",subtopic:"Objective Questions",question:"Evaporation takes place at ______ temperature.",blankAnswer:"all",answer:"Evaporation takes place at all temperatures.",teacherTip:'Evaporation is a "24/7" process.',examTip:'Use "all temperatures" to define evaporation.'},
{id:"c6fb3",topicId:"ch6-heat",type:"fill_blank",subtopic:"Objective Questions",question:"Gases expand ______ than the liquids.",blankAnswer:"more",answer:"Gases expand more than liquids.",teacherTip:'Gases are the "expansion champions".',examTip:'Order: Gas > Liquid > Solid.'},
{id:"c6fb4",topicId:"ch6-heat",type:"fill_blank",subtopic:"Objective Questions",question:"Iron expands ______ than copper.",blankAnswer:"less",answer:"Iron expands less than copper. Copper has higher coefficient of linear expansion.",teacherTip:'Copper "grows" faster than iron.',examTip:'This is the principle behind bimetallic strips.'},
// MATCH
{id:"c6m1",topicId:"ch6-heat",type:"match",subtopic:"Objective Questions",question:"Match Column A with Column B",pairs:[{left:"Blowing air increases",right:"evaporation"},{left:"Increase in pressure increases",right:"boiling point"},{left:"Thermal expansion",right:"increase in inter-molecular separation"},{left:"Invar",right:"pendulum of a clock"},{left:"Pyrex glass",right:"cooking utensils"}],answer:"Blowing air→evaporation, Increase in pressure→boiling point, Thermal expansion→inter-molecular separation, Invar→pendulum, Pyrex glass→cooking utensils",teacherTip:'Invar has very low expansion — used for precision instruments.',examTip:'Pyrex glass has low expansion — doesn\'t crack when heated.'},
// MCQs
{id:"c6mcq1",topicId:"ch6-heat",type:"mcq",subtopic:"Objective Questions",question:"In evaporation:",options:["all molecules escape","only surface molecules escape","temperature of liquid rises","molecules get attracted within"],correctOption:1,answer:"Only surface molecules escape. Evaporation is a surface phenomenon.",teacherTip:'"Surface Only" for evaporation, "Whole Bulk" for boiling.',examTip:'Distinguish surface molecules from bulk molecules.'},

// ============================== CHAPTER 7: SOUND ==============================
// NOTES
{id:"c7n1",topicId:"ch7-sound",type:"note",subtopic:"Sound - Nature & Propagation",content:'SOUND is energy that produces sensation of hearing. Produced by vibration. Needs a medium for propagation — cannot travel in vacuum. Speed: solids (5000 m/s in steel) > liquids (1500 m/s in water) > gases (330 m/s in air).',explanation:'Sound needs molecules to carry energy. In space (vacuum), there is complete silence.',teacherTip:'Solids are "fast lanes" for sound waves.',examTip:'Memorize speed of sound in air ≈ 330-340 m/s.'},
{id:"c7n2",topicId:"ch7-sound",type:"note",subtopic:"Sound Wave Properties",content:'Sound travels as LONGITUDINAL waves (compressions & rarefactions).\nAMPLITUDE: Maximum displacement from mean position → determines LOUDNESS.\nFREQUENCY (f): Vibrations per second, measured in Hertz (Hz). f = 1/T.\nWAVELENGTH (λ): Distance between two consecutive compressions. Unit: metre.',explanation:'Compressions are areas of high pressure, rarefactions are low pressure areas.',teacherTip:'Amplitude = "height" of vibration. Frequency = "speed" of vibration.',examTip:'1 Hz = 1 vibration per second.'},
{id:"c7n3",topicId:"ch7-sound",type:"note",subtopic:"Characteristics of Sound",content:'Three characteristics: (i) LOUDNESS — depends on amplitude. Unit: decibel (dB). Safe limit: 0-80 dB.\n(ii) PITCH — depends on frequency. High frequency = shrill/high pitch.\n(iii) QUALITY (Timbre) — depends on waveform. Distinguishes instruments playing same note.',explanation:'These three properties let us identify different sounds — a whisper vs shout, flute vs piano.',teacherTip:'Remember "L-A-P-F": Loudness-Amplitude, Pitch-Frequency.',examTip:'List all three when asked for characteristics of sound.'},
// TRUE/FALSE
{id:"c7tf1",topicId:"ch7-sound",type:"true_false",subtopic:"Objective Questions",question:"When sound propagates in air, it does not carry energy with it.",correctAnswer:"false",answer:"False. Sound IS a form of energy that travels through air by vibrating particles.",teacherTip:'If sound didn\'t carry energy, it couldn\'t move your eardrum.',examTip:'All waves are transporters of energy.'},
{id:"c7tf2",topicId:"ch7-sound",type:"true_false",subtopic:"Objective Questions",question:"In a longitudinal wave, compression and rarefaction are formed.",correctAnswer:"true",answer:"True. Longitudinal waves consist of high-pressure (compression) and low-pressure (rarefaction) regions.",teacherTip:'Compression = "Squeeze", Rarefaction = "Stretch".',examTip:'Mention both terms when describing sound waves.'},
{id:"c7tf3",topicId:"ch7-sound",type:"true_false",subtopic:"Objective Questions",question:"The frequency is measured in second.",correctAnswer:"false",answer:"False. Frequency is measured in Hertz (Hz). Second is the unit for Time Period.",teacherTip:'Hertz = 1/second.',examTip:'Frequency is Hz, Time is s.'},
{id:"c7tf4",topicId:"ch7-sound",type:"true_false",subtopic:"Objective Questions",question:"The pitch of sound depends on frequency.",correctAnswer:"true",answer:"True. Higher frequency = higher pitch. Pitch and frequency are directly related.",teacherTip:'Faster vibrations mean higher notes.',examTip:'Pitch is directly proportional to Frequency.'},
{id:"c7tf5",topicId:"ch7-sound",type:"true_false",subtopic:"Objective Questions",question:"Decibel is the unit of pitch of a sound.",correctAnswer:"false",answer:"False. Decibel (dB) is the unit of LOUDNESS. Pitch is related to frequency (Hz).",teacherTip:'Decibels = "volume", Hertz = "note".',examTip:'Don\'t confuse: Loudness (dB) vs Pitch (Hz).'},
// FILL IN BLANKS
{id:"c7fb1",topicId:"ch7-sound",type:"fill_blank",subtopic:"Objective Questions",question:"The time period of a wave is 2 s. Its frequency is ______ Hz.",blankAnswer:"0.5",answer:"f = 1/T = 1/2 = 0.5 Hz.",teacherTip:'f = 1/T. Simple division.',examTip:'Show calculation f = 1/T for partial credit.'},
{id:"c7fb2",topicId:"ch7-sound",type:"fill_blank",subtopic:"Objective Questions",question:"A tuning fork produces sound of ______ frequency.",blankAnswer:"single",answer:"A tuning fork produces a pure tone of single frequency.",teacherTip:'Tuning forks are "standard rulers" for sound frequency.',examTip:'Use "pure tone" to describe a tuning fork.'},
// MATCH
{id:"c7m1",topicId:"ch7-sound",type:"match",subtopic:"Objective Questions",question:"Match Column A with Column B",pairs:[{left:"Amplitude",right:"maximum displacement on either side"},{left:"Frequency",right:"1/time period"},{left:"Loudness",right:"amplitude"},{left:"Pitch",right:"frequency"},{left:"Wave form",right:"presence of other frequencies"}],answer:"Amplitude→max displacement, Frequency→1/T, Loudness→amplitude, Pitch→frequency, Waveform→other frequencies",teacherTip:'L-A-P-F: Loudness-Amplitude, Pitch-Frequency.',examTip:'Cross-check each pair before finalizing.'},
// MCQs
{id:"c7mcq1",topicId:"ch7-sound",type:"mcq",subtopic:"Objective Questions",question:"Sound cannot travel in:",options:["solid","liquid","gas","vacuum"],correctOption:3,answer:"Vacuum. Sound requires a material medium. Space is silent.",teacherTip:'"In space, no one can hear you scream."',examTip:'Always choose vacuum as where sound cannot travel.'},
{id:"c7mcq2",topicId:"ch7-sound",type:"mcq",subtopic:"Objective Questions",question:"The safe limit of loudness of audible sound is:",options:["0 to 80 dB","above 80 dB","120 dB","above 120 dB"],correctOption:0,answer:"0 to 80 dB. Sounds above 80 dB can cause hearing damage.",teacherTip:'Above 80 dB = danger zone for ears.',examTip:'Memorize 80 dB as the safe limit.'},
// SHORT ANSWER
{id:"c7sa1",topicId:"ch7-sound",type:"short_answer",subtopic:"Short/Long Answer",question:"Define sound. How is it produced?",answer:'Sound is a form of energy which produces the sensation of hearing. It is produced by the vibration of a body.\n\nSound needs a material medium for propagation and cannot travel in vacuum. It travels as longitudinal waves.',teacherTip:'Without vibration, there is no sound.',examTip:'Define sound as a form of energy requiring a vibrating source.'},
{id:"c7sa2",topicId:"ch7-sound",type:"short_answer",subtopic:"Short/Long Answer",question:"State the three characteristics of sound. What does each depend on?",answer:'(i) LOUDNESS — depends on amplitude of wave. Unit: decibel (dB).\n(ii) PITCH — depends on frequency. More frequency = high pitch (shrill).\n(iii) QUALITY (Timbre) — depends on wave form. Distinguishes different instruments.',teacherTip:'Big Amplitude = Big Loudness. Fast vibration = High Pitch.',examTip:'List all three with their dependencies.'},
{id:"c7sa3",topicId:"ch7-sound",type:"short_answer",subtopic:"Short/Long Answer",question:"Define: amplitude, frequency, wavelength, time period.",answer:'AMPLITUDE: Maximum displacement of particle from mean position.\nFREQUENCY: Number of vibrations per second. Unit: Hz. f = 1/T.\nWAVELENGTH (λ): Distance between two consecutive compressions (or rarefactions). Unit: metre.\nTIME PERIOD (T): Time for one complete vibration. Unit: second. T = 1/f.',teacherTip:'Frequency and Time Period are inverses of each other.',examTip:'Include units for each quantity.'},

// ============================== CHAPTER 8: ELECTRICITY ==============================
// NOTES
{id:"c8n1",topicId:"ch8-electricity",type:"note",subtopic:"Electric Current & Potential Difference",content:'ELECTRICITY: Rate of flow of electrons. i = q/t. S.I. unit of current: Ampere (A). S.I. unit of charge: Coulomb (C).\nPOTENTIAL DIFFERENCE (V): Work done per unit charge. V = W/Q. Unit: Volt (V).\nElectrical Energy W = VIt.',explanation:'Current is like water flowing through a pipe. Potential difference is the "push" from a battery.',teacherTip:'A battery is like a "pump" for electrons.',examTip:'Always write i = q/t and define each symbol.'},
{id:"c8n2",topicId:"ch8-electricity",type:"note",subtopic:"Power & Energy Units",content:'POWER P = VI = W/t. Unit: Watt (W). 1 W = 1 V × 1 A.\nElectrical Energy = VIt. S.I. unit: Joule. Commercial unit: kWh.\n1 kWh = 3.6 × 10⁶ J = 1 unit (for electricity bills).',explanation:'Power tells how quickly an appliance uses energy. kWh is what the electric company uses for billing.',teacherTip:'Power = "Energy per Second".',examTip:'Don\'t confuse kW (power) with kWh (energy).'},
{id:"c8n3",topicId:"ch8-electricity",type:"note",subtopic:"Power Transmission",content:'Power generated at 11 kV → stepped up to 132 kV at grid sub-station (to minimize energy loss) → stepped down to 33 kV at main sub-station → finally to 220 V for household supply.',explanation:'High voltage transmission reduces energy loss in wires. Multiple step-downs bring it to safe 220V for homes.',teacherTip:'Step up for long distance, step down for safety.',examTip:'Remember sequence: 11 kV → 132 kV → 33 kV → 220 V.'},
{id:"c8n4",topicId:"ch8-electricity",type:"note",subtopic:"Safety Devices",content:'EARTHING: Safety device at zero potential — protects from electric shock. Connected to metal body of appliances.\nFUSE: Limits current. Has high resistance and low melting point. Connected in LIVE wire.\nSHORT CIRCUIT: Live wire touches neutral wire due to damaged insulation.\nColour coding: Live = Red/Brown, Neutral = Black/Blue, Earth = Green/Yellow.',explanation:'Fuse melts to break circuit when current is too high. MCBs are modern replacements. Appliances are connected in parallel.',teacherTip:'A fuse "gives its life" to save your expensive TV!',examTip:'Always list "Low Melting Point" and "High Resistance" for fuse wire.'},
// TRUE/FALSE
{id:"c8tf1",topicId:"ch8-electricity",type:"true_false",subtopic:"Objective Questions",question:"A fuse wire has a high melting point.",correctAnswer:"false",answer:"False. A fuse wire has a LOW melting point so it melts quickly when current is too high, breaking the circuit.",teacherTip:'Fuse = "weak link" designed to break first for safety.',examTip:'State that melting point is LOW.'},
{id:"c8tf2",topicId:"ch8-electricity",type:"true_false",subtopic:"Objective Questions",question:"Flow of protons constitutes electric current.",correctAnswer:"false",answer:"False. Electric current is the flow of ELECTRONS. Protons stay in the nucleus.",teacherTip:'Electrons "run", Protons "stay put".',examTip:'Define current as "rate of flow of electrons."'},
{id:"c8tf3",topicId:"ch8-electricity",type:"true_false",subtopic:"Objective Questions",question:"S.I. unit and commercial unit of electrical energy are same.",correctAnswer:"false",answer:"False. S.I. unit is Joule (J). Commercial unit is kilowatt-hour (kWh). 1 kWh = 3.6 × 10⁶ J.",teacherTip:'Joules for "Science", kWh for "Bills".',examTip:'Remember 1 kWh = 3.6 × 10⁶ J.'},
{id:"c8tf4",topicId:"ch8-electricity",type:"true_false",subtopic:"Objective Questions",question:"Overloading of electric current in circuits can lead to short circuiting.",correctAnswer:"true",answer:"True. Overloaded wires get extremely hot, melting insulation. Bare wires may touch causing short circuit.",teacherTip:'Heat from overloading is a wire\'s worst enemy.',examTip:'"Melting of insulation" links overloading to short circuits.'},
{id:"c8tf5",topicId:"ch8-electricity",type:"true_false",subtopic:"Objective Questions",question:"The earth wire protects us from an electric shock.",correctAnswer:"true",answer:"True. Earth wire provides a safe route for stray electricity to go into the ground instead of through your body.",teacherTip:'Earth wire = "emergency exit" for electricity.',examTip:'Earth wire is connected to the "metal body" of the appliance.'},
{id:"c8tf6",topicId:"ch8-electricity",type:"true_false",subtopic:"Objective Questions",question:"A fuse is connected to the live wire.",correctAnswer:"true",answer:"True. Fuse must be in the live wire so that when it melts, the appliance is fully disconnected from power.",teacherTip:'Putting fuse in "Live" wire cuts power at the source.',examTip:'Safety devices (fuse, switch) are always in the Live wire.'},
{id:"c8tf7",topicId:"ch8-electricity",type:"true_false",subtopic:"Objective Questions",question:"In a cable, the green wire is the live wire.",correctAnswer:"false",answer:"False. Green (or green-yellow) wire is the EARTH wire. Live wire is Red or Brown.",teacherTip:'"Green is the Ground."',examTip:'Live = Red/Brown, Earth = Green/Yellow, Neutral = Black/Blue.'},
// FILL IN BLANKS
{id:"c8fb1",topicId:"ch8-electricity",type:"fill_blank",subtopic:"Objective Questions",question:"The unit in which we pay for electricity is ______.",blankAnswer:"kWh",answer:"The commercial unit of electrical energy is kWh (kilowatt-hour). 1 kWh = 1 unit.",teacherTip:'kWh is the "unit of the bill".',examTip:'Don\'t confuse kW (power) with kWh (energy).'},
{id:"c8fb2",topicId:"ch8-electricity",type:"fill_blank",subtopic:"Objective Questions",question:"1 kWh = ______ J.",blankAnswer:"3.6 × 10⁶",answer:"1 kWh = 3,600,000 J = 3.6 × 10⁶ J.",teacherTip:'3.6 million joules in one unit of electricity.',examTip:'Memorize this conversion factor.'},
{id:"c8fb3",topicId:"ch8-electricity",type:"fill_blank",subtopic:"Objective Questions",question:"The colour of the earth wire is ______.",blankAnswer:"green",answer:"Earth wire is Green or Green-Yellow.",teacherTip:'"Green is the Ground."',examTip:'Know colour codes: Live=Red/Brown, Neutral=Black/Blue, Earth=Green/Yellow.'},
{id:"c8fb4",topicId:"ch8-electricity",type:"fill_blank",subtopic:"Objective Questions",question:"A fuse wire should have high resistance and ______ melting point.",blankAnswer:"low",answer:"A fuse wire should have high resistance and LOW melting point.",teacherTip:'Low melting point means it melts quickly to break circuit.',examTip:'Both properties are important for fuse wire.'},
// MCQs
{id:"c8mcq1",topicId:"ch8-electricity",type:"mcq",subtopic:"Objective Questions",question:"The S.I. unit of electric current is:",options:["volt","watt","ampere","ohm"],correctOption:2,answer:"Ampere (A). Current i = q/t, measured in Amperes.",teacherTip:'"Amp" is short for Ampere.',examTip:'Remember C-A-V-J-W units.'},
{id:"c8mcq2",topicId:"ch8-electricity",type:"mcq",subtopic:"Objective Questions",question:"1 kWh is equal to:",options:["3600 J","36000 J","360000 J","3600000 J"],correctOption:3,answer:"3,600,000 J = 3.6 × 10⁶ J.",teacherTip:'1 kW × 3600 seconds = 3,600,000 J.',examTip:'Show the calculation: 1000 W × 3600 s.'},
{id:"c8mcq3",topicId:"ch8-electricity",type:"mcq",subtopic:"Objective Questions",question:"The voltage of electricity supplied to our houses is:",options:["11 kV","132 kV","33 kV","220 V"],correctOption:3,answer:"220 V. This is the standard safe voltage for household supply.",teacherTip:'220 V is the magic number for home electricity.',examTip:'Know the full chain: 11→132→33 kV→220 V.'},
// SHORT ANSWER
{id:"c8sa1",topicId:"ch8-electricity",type:"short_answer",subtopic:"Short/Long Answer",question:"Define electric current. State its S.I. unit.",answer:'Electric current is the rate of flow of charge (electrons) through a conductor.\ni = q/t where q = charge in coulombs, t = time in seconds.\nS.I. unit: Ampere (A).',teacherTip:'Current = "speed" of the electricity river.',examTip:'Write formula i = q/t and define each symbol.'},
{id:"c8sa2",topicId:"ch8-electricity",type:"short_answer",subtopic:"Short/Long Answer",question:"Define potential difference and power. State their units.",answer:'POTENTIAL DIFFERENCE: Work done in moving a unit positive charge from one point to another. V = W/Q. Unit: Volt (V).\n\nPOWER: Rate of doing work. P = W/t = VI. Unit: Watt (W).\n1 Watt = 1 Volt × 1 Ampere.',teacherTip:'Use the "W-Q-V" triangle to remember formulas.',examTip:'Ensure time is in seconds for standard formula.'},
{id:"c8sa3",topicId:"ch8-electricity",type:"short_answer",subtopic:"Short/Long Answer",question:"What is earthing? Why is it done?",answer:'Earthing is a safety device that puts an appliance at zero potential. A thick copper wire connects the metal body of an appliance to a copper plate buried deep in the ground.\n\nIf the live wire touches the metal body accidentally, the current flows through the earth wire to the ground instead of through the user, preventing electric shock.',teacherTip:'Earth is like a giant sponge that soaks up extra electricity.',examTip:'Explain that earthing protects from "electric shocks."'},
{id:"c8sa4",topicId:"ch8-electricity",type:"short_answer",subtopic:"Short/Long Answer",question:"What is a fuse? State two properties of fuse wire. Where is it connected?",answer:'FUSE: A safety device used to limit current in an electric circuit. It melts and breaks the circuit when current exceeds safe limit.\n\nProperties of fuse wire:\n(i) High resistance\n(ii) Low melting point\n\nFuse is always connected in the LIVE wire.',teacherTip:'A fuse "sacrifices itself" to protect appliances.',examTip:'Both properties are essential for full marks.'},
{id:"c8sa5",topicId:"ch8-electricity",type:"short_answer",subtopic:"Short/Long Answer",question:"What is short circuiting? What is overloading? How can they be prevented?",answer:'SHORT CIRCUITING: When insulation breaks and live wire touches neutral wire directly. Causes sparking and fire.\n\nOVERLOADING: When too many appliances draw more current than the circuit is designed for.\n\nPrevention: Use fuse or MCB (Miniature Circuit Breaker) in the live wire. Use proper insulation. Don\'t plug too many appliances in one socket.',teacherTip:'Short circuit = "accidental shortcut" for electricity.',examTip:'Define both terms and mention prevention methods.'},
{id:"c8sa6",topicId:"ch8-electricity",type:"short_answer",subtopic:"Short/Long Answer",question:"State the colour coding of wires. Why are appliances connected in parallel?",answer:'Colour Coding:\n• Live wire: Red or Brown\n• Neutral wire: Black or Light Blue\n• Earth wire: Green or Yellow\n\nAppliances are connected in PARALLEL because:\n(i) Each appliance gets full 220 V voltage\n(ii) If one appliance fails, others continue to work\n(iii) Each can be switched on/off independently',teacherTip:'"Red is for Danger" (Live), "Green is for Earth" (Ground).',examTip:'Memorize both old and new colour codes.'},
{id:"c8sa7",topicId:"ch8-electricity",type:"short_answer",subtopic:"Short/Long Answer",question:"Describe the transmission of electric power from generating station to homes.",answer:'1. GENERATING STATION: Power generated at 11 kV\n2. GRID SUB-STATION: Stepped UP to 132 kV (to minimize energy loss in long-distance transmission)\n3. MAIN SUB-STATION: Stepped down to 33 kV\n4. CITY SUB-STATION: Stepped down to 220 V for household supply\n\nHigh voltage reduces current, which reduces heat loss (I²R) in transmission wires.',teacherTip:'Step up for long distance, step down for safety.',examTip:'Know the sequence: 11 kV → 132 kV → 33 kV → 220 V.'},
];
