// ============================================================
// StudyHub — Chemical Index: every element and compound in the Class 8 chemistry book,
// each with a one-line description and a link to the note where the book teaches it.
// Elements: symbol -> [valency, description, noteId]. Compounds: [formula, name, kind, description, noteId].
// Atomic masses use the book's rounded values (Cl = 35.5); the rest of the table is in chemistry-elements.js.
// ============================================================
const CHEM_BOOK_MASS = { H: 1, He: 4, Li: 7, Be: 9, B: 11, C: 12, N: 14, O: 16, F: 19, Ne: 20, Na: 23, Mg: 24, Al: 27, Si: 28, P: 31, S: 32, Cl: 35.5, Ar: 40, K: 39, Ca: 40, Mn: 55, Fe: 56, Cu: 64, Zn: 65, Br: 80, Ag: 108, I: 127, Ba: 137, Hg: 201, Pb: 207 };
const CHEM_LATIN = { Na: 'Natrium', K: 'Kalium', Fe: 'Ferrum', Cu: 'Cuprum', Ag: 'Argentum', Au: 'Aurum', Hg: 'Hydrargyrum', Pb: 'Plumbum', Sn: 'Stannum', Sb: 'Stibium' };

const CHEM_BOOK_ELEMENTS = {
  H: ['1', 'Lightest gas, most abundant element in the universe. Burns with a pale-blue flame but does not support burning. Made in the lab from zinc + dilute HCl; H₂ is the fuel in rockets and turns oils into vanaspati ghee.', 'cn-c7-n01'],
  He: ['0', 'Noble gas — monoatomic and unreactive, with a complete outer shell (duplet). Safe replacement for hydrogen in weather balloons.', 'cn-c3-n02'],
  Li: ['1', 'Alkali metal with one outer electron; loses it to form Li⁺. Its atomic mass is 6.9 (taken as 7).', 'cn-c4-n09'],
  Be: ['2', 'Light metal with two outer electrons; forms Be²⁺.', 'cn-c4-n09'],
  B: ['3', 'A metalloid — shows some properties of metals and some of non-metals. Hard solid.', 'cn-c3-n02'],
  C: ['4', 'Non-metal with four valence electrons; links with itself (catenation) to make countless compounds. Free forms: diamond, graphite, fullerene, coal, charcoal.', 'cn-c9-n01'],
  N: ['3', 'Gas making up most of air (b.p. −196°C). Exists as N₂ molecules. Used in the Haber process to make ammonia.', 'cn-c3-n03'],
  O: ['2', 'Gas that supports burning and breathing; exists as O₂ (and O₃ ozone). Combines with metals to make basic oxides, with non-metals to make acidic oxides.', 'cn-c3-n03'],
  F: ['1', 'Most reactive halogen; gains one electron to form F⁻ and completes its octet.', 'cn-c4-n09'],
  Ne: ['0', 'Noble gas — monoatomic, unreactive, found in traces in air. Outer shell complete (2,8).', 'cn-c3-n02'],
  Na: ['1', 'Soft, very reactive metal. Loses one electron to form Na⁺. Kept under kerosene to keep it from air and moisture; reacts with cold water to give NaOH + H₂.', 'cn-c7-n04'],
  Mg: ['2', 'Burns with a dazzling white light to form white MgO — and gains mass doing so. Even burns in CO₂ (2Mg + CO₂ → 2MgO + C).', 'cn-c6-n04'],
  Al: ['3', 'Light metal forming Al³⁺. Its oxide Al₂O₃ is amphoteric — reacts with both acids and NaOH.', 'cn-c6-n09'],
  Si: ['4', 'A metalloid found as sand/silica (SiO₂). Four valence electrons.', 'cn-c3-n02'],
  P: ['3, 5', 'Non-metal that exists as P₄ molecules (atomicity 4). Valency 3 in PCl₃ and 5 in PCl₅.', 'cn-c3-n03'],
  S: ['2, 4, 6', 'Yellow non-metal that exists as S₈ molecules (atomicity 8). Dissolves in carbon disulphide. Shows valency 2, 4 and 6; combines with iron to make FeS.', 'cn-c3-n03'],
  Cl: ['1', 'Greenish-yellow halogen gas (Cl₂). Atomic mass 35.5 because its isotopes Cl-35 and Cl-37 are averaged. Displaces Br₂ from KBr and I₂ from KI.', 'cn-c4-n11'],
  Ar: ['0', 'Noble gas — monoatomic, unreactive, complete octet (2,8,8). Found in traces in air.', 'cn-c3-n02'],
  K: ['1', 'Soft, very reactive metal, stored under kerosene. Configuration 2,8,8,1 (not 2,8,9) because the outer shell cannot exceed 8.', 'cn-c4-n09'],
  Ca: ['2', 'Reactive metal forming Ca²⁺ (2,8,8,2). Occurs as limestone, marble and chalk (CaCO₃); reacts with cold water to give Ca(OH)₂ + H₂.', 'cn-c9-n01'],
  Cr: ['3', 'Metal with symbol Cr (not C or Co). Its oxide Cr₂O₃ is part of the catalyst in the Bosch process; forms Cr³⁺.', 'cn-c7-n05'],
  Mn: ['2', 'Metal forming Mn²⁺ (manganous). Its oxide MnO₂ is a positive catalyst for decomposing KClO₃.', 'cn-c6-n03'],
  Co: ['—', 'Magnetic metal — written Co, never CO (that is carbon monoxide). Blue anhydrous cobalt chloride turns pink with water.', 'cn-c8-n09'],
  Ni: ['2', 'Magnetic metal forming Ni²⁺. Used as a catalyst with hydrogen for making vanaspati ghee.', 'cn-c7-n08'],
  Fe: ['2, 3', 'Metal, symbol from Latin Ferrum. Ferrous Fe²⁺ (lower) and ferric Fe³⁺ (higher). Rusts in air + water; magnetic; with sulphur makes non-magnetic FeS; catalyst in the Haber process.', 'cn-c2-n03'],
  Cu: ['1, 2', 'Reddish metal, from Latin Cuprum. Cuprous Cu⁺ and cupric Cu²⁺. Displaces silver from AgNO₃ and is displaced by zinc from CuSO₄.', 'cn-c6-n06'],
  Zn: ['2', 'Bluish-white metal, forms Zn²⁺. Granulated zinc + dilute HCl gives hydrogen in the lab. ZnO is amphoteric.', 'cn-c7-n03'],
  As: ['—', 'A metalloid (arsenic) — properties of both metals and non-metals.', 'cn-c3-n02'],
  Ge: ['—', 'A metalloid (germanium) — properties of both metals and non-metals.', 'cn-c3-n02'],
  Br: ['1', 'Halogen that is a reddish-brown LIQUID at room temperature (one of the two liquid elements). Displaced from KBr by chlorine.', 'cn-c6-n06'],
  Kr: ['0', 'Noble gas — monoatomic and unreactive; found in traces in air.', 'cn-c3-n02'],
  Mo: ['—', 'Metal used as a promoter (with an iron catalyst) in the Haber process — it raises the catalyst’s efficiency.', 'cn-c5-n09'],
  Ag: ['1, 2', 'Shiny metal, from Latin Argentum. Below hydrogen in the activity series. Argentous Ag⁺ and argentic Ag²⁺. Silver chloride AgCl is a white precipitate.', 'cn-c6-n06'],
  Sn: ['2, 4', 'Metal, from Latin Stannum. Stannous Sn²⁺ (lower) and stannic Sn⁴⁺ (higher). Used in the alloy bronze.', 'cn-c5-n03'],
  Sb: ['—', 'A metalloid, from Latin Stibium (antimony).', 'cn-c5-n01'],
  Te: ['—', 'A metalloid (tellurium).', 'cn-c3-n02'],
  I: ['1', 'Shiny non-metal that sublimes on heating; dissolves in alcohol. Isotope iodine is used against goitre. Displaced from KI by chlorine.', 'cn-c1-n08'],
  Xe: ['0', 'Noble gas — monoatomic, unreactive, found in traces in air.', 'cn-c3-n02'],
  Ba: ['2', 'Metal forming Ba²⁺. BaCl₂ + Na₂SO₄ gives white BaSO₄ — the precipitate used to test the law of conservation of mass.', 'cn-c1-n10'],
  W: ['—', 'Metal (tungsten) that conducts poorly — an exception to “metals are good conductors”.', 'cn-c3-n02'],
  Pt: ['4', 'Least reactive metal at the bottom of the activity series; forms Pt⁴⁺. Acts as a catalyst for hydrogenation.', 'cn-c6-n06'],
  Au: ['—', 'Precious metal, from Latin Aurum. Very unreactive — near the bottom of the activity series.', 'cn-c5-n01'],
  Hg: ['1, 2', 'The only metal that is liquid at room temperature (bromine is the only liquid non-metal). Latin Hydrargyrum. Mercurous Hg⁺ and mercuric Hg²⁺. 2HgO → 2Hg + O₂ on heating.', 'cn-c6-n05'],
  Pb: ['2, 4', 'Heavy metal, from Latin Plumbum. Plumbous Pb²⁺ and plumbic Pb⁴⁺. PbO is amphoteric and pale yellow.', 'cn-c5-n03'],
  Rn: ['0', 'Radioactive noble gas — the last of the six noble gases.', 'cn-c3-n02'],
  Ra: ['—', 'Radioactive metal; the book lists its symbol Ra.', 'cn-c5-n01'],
  U: ['—', 'Radioactive metal; an isotope of uranium is used as fuel in nuclear reactors.', 'cn-c4-n11']
};

// kind: gas | oxide | acid | base | salt | hydrate | organic | other
const CHEM_BOOK_COMPOUNDS = [
  ['H2O', 'Water', 'other', 'H : O = 1 : 8 by mass and 2 : 1 by volume. Universal solvent; boils at 100°C, freezes at 0°C; densest at 4°C. Neutral oxide.', 'cn-c8-n01'],
  ['H2O2', 'Hydrogen peroxide', 'other', 'Its decomposition is slowed by phosphoric acid — the book’s example of a negative catalyst.', 'cn-c6-n03'],
  ['NH3', 'Ammonia', 'gas', 'Made by the Haber process: N₂ + 3H₂ ⇌ 2NH₃ (Fe catalyst, Mo promoter). With HCl gives white fumes of NH₄Cl. Used with CO₂ to make urea.', 'cn-c5-n09'],
  ['CO2', 'Carbon dioxide', 'oxide', 'Acidic oxide, 1.5× heavier than air; turns lime water milky. Made from marble + dilute HCl. Solid form is dry ice (−78°C). A greenhouse gas; used in fire extinguishers.', 'cn-c9-n09'],
  ['CO', 'Carbon monoxide', 'oxide', 'Neutral oxide from incomplete combustion; highly poisonous (forms carboxyhaemoglobin). A strong reducing agent — Fe₂O₃ + 3CO → 2Fe + 3CO₂.', 'cn-c9-n11'],
  ['SO2', 'Sulphur dioxide', 'oxide', 'Acidic oxide (molecular mass 64). With water gives sulphurous acid H₂SO₃.', 'cn-c6-n09'],
  ['SO3', 'Sulphur trioxide', 'oxide', 'Acidic oxide; with water gives sulphuric acid H₂SO₄.', 'cn-c6-n09'],
  ['NO2', 'Nitrogen dioxide', 'oxide', 'Reddish-brown acidic gas, given off when lead nitrate is heated.', 'cn-c6-n05'],
  ['NO', 'Nitric oxide', 'oxide', 'Neutral oxide; made when N₂ and O₂ combine at 3000°C (absorbs heat — endothermic).', 'cn-c3-n04'],
  ['N2O', 'Nitrous oxide', 'oxide', 'Neutral oxide; also a greenhouse gas.', 'cn-c6-n09'],
  ['P2O5', 'Phosphorus pentoxide', 'oxide', 'Acidic oxide of phosphorus (valency 5).', 'cn-c6-n09'],
  ['Na2O', 'Sodium oxide', 'oxide', 'Basic oxide of a metal; reacts with water to give the alkali NaOH.', 'cn-c6-n09'],
  ['MgO', 'Magnesium oxide', 'oxide', 'White basic oxide formed when magnesium burns in air: 2Mg + O₂ → 2MgO.', 'cn-c6-n04'],
  ['CaO', 'Calcium oxide (quicklime)', 'oxide', 'Basic oxide made by heating CaCO₃. Reacts with water giving slaked lime and lots of heat (exothermic); a drying agent (hygroscopic); treats acidic soil.', 'cn-c6-n08'],
  ['Al2O3', 'Aluminium oxide', 'oxide', 'Amphoteric oxide — reacts with acids and with NaOH (giving sodium aluminate).', 'cn-c6-n09'],
  ['ZnO', 'Zinc oxide', 'oxide', 'Amphoteric oxide; with NaOH gives sodium zincate.', 'cn-c6-n09'],
  ['PbO', 'Lead(II) oxide', 'oxide', 'Amphoteric, pale yellow oxide; reduced to lead by hydrogen. With NaOH gives sodium plumbite.', 'cn-c6-n09'],
  ['CuO', 'Copper(II) oxide', 'oxide', 'Black oxide; hydrogen reduces it to copper: CuO + H₂ → Cu + H₂O (a redox reaction).', 'cn-c7-n09'],
  ['HgO', 'Mercuric oxide', 'oxide', 'Decomposes on heating: 2HgO → 2Hg + O₂.', 'cn-c6-n05'],
  ['Fe2O3', 'Iron(III) oxide', 'oxide', 'Reddish-brown — the colour of rust. Catalyst in the Bosch process; reduced by CO to iron.', 'cn-c2-n05'],
  ['Fe3O4', 'Triiron tetroxide', 'oxide', 'Formed when red-hot iron reacts with steam: 3Fe + 4H₂O ⇌ Fe₃O₄ + 4H₂ (a reversible reaction).', 'cn-c7-n04'],
  ['SiO2', 'Silicon dioxide (silica, sand)', 'oxide', 'Sand and silica; silica gel is a drying agent.', 'cn-c3-n04'],
  ['MnO2', 'Manganese dioxide', 'oxide', 'Positive catalyst — cuts the decomposition of KClO₃ from 700°C to about 300°C.', 'cn-c6-n03'],
  ['HCl', 'Hydrochloric acid (hydrogen chloride)', 'acid', 'Strong acid; a strong electrolyte. Zinc + dilute HCl gives hydrogen; marble + dilute HCl gives CO₂. Formed by H₂ + Cl₂ in sunlight.', 'cn-c7-n03'],
  ['H2SO4', 'Sulphuric acid', 'acid', 'Strong acid (molecular mass 98). Conc. H₂SO₄ is hygroscopic — a drying agent. Not used to make CO₂ because insoluble CaSO₄ coats the marble.', 'cn-c5-n06'],
  ['HNO3', 'Nitric acid', 'acid', 'Strong oxidising acid, so not used to make hydrogen (it oxidises the H₂ to water).', 'cn-c7-n04'],
  ['H2CO3', 'Carbonic acid', 'acid', 'Weak acid formed when CO₂ dissolves in water.', 'cn-c6-n09'],
  ['H2SO3', 'Sulphurous acid', 'acid', 'Formed when SO₂ dissolves in water.', 'cn-c6-n09'],
  ['CH3COOH', 'Acetic acid (vinegar)', 'acid', 'Weak acid and a weak electrolyte; vinegar is a solution of it. Wasp stings (alkaline) are treated with vinegar.', 'cn-c7-n02'],
  ['H2S', 'Hydrogen sulphide', 'gas', 'Rotten-egg smelling gas made by H₂ + S.', 'cn-c7-n07'],
  ['NaOH', 'Sodium hydroxide (caustic soda)', 'base', 'Strong alkali; deliquescent. Dissolves amphoteric oxides; a strong electrolyte.', 'cn-c6-n09'],
  ['KOH', 'Potassium hydroxide (caustic potash)', 'base', 'Strong alkali; can absorb CO₂ from a gas mixture.', 'cn-c7-n05'],
  ['Ca(OH)2', 'Calcium hydroxide (slaked lime, lime water)', 'base', 'Made from quicklime + water. Its solution, lime water, turns milky with CO₂.', 'cn-c9-n09'],
  ['NH4OH', 'Ammonium hydroxide', 'base', 'Weak alkali and weak electrolyte (only partly dissociates).', 'cn-c7-n02'],
  ['Mg(OH)2', 'Magnesium hydroxide (milk of magnesia)', 'base', 'Antacid — neutralises excess stomach acid.', 'cn-c6-n07'],
  ['Cu(OH)2', 'Copper(II) hydroxide', 'base', 'Blue precipitate: CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄.', 'cn-c6-n07'],
  ['Fe(OH)2', 'Iron(II) hydroxide', 'base', 'Dirty-green precipitate.', 'cn-c6-n02'],
  ['NaCl', 'Sodium chloride (common salt)', 'salt', 'Table salt; strong electrolyte. Not itself deliquescent — table salt turns damp in monsoon due to MgCl₂ and CaCl₂ impurities.', 'cn-c8-n08'],
  ['KCl', 'Potassium chloride', 'salt', 'Product when potassium chlorate decomposes: 2KClO₃ → 2KCl + 3O₂.', 'cn-c6-n05'],
  ['KClO3', 'Potassium chlorate', 'salt', 'Decomposes to KCl and oxygen; MnO₂ catalyst speeds it up.', 'cn-c6-n03'],
  ['KNO3', 'Potassium nitrate', 'salt', 'Separated from NaCl by fractional crystallisation; also an ingredient of gunpowder.', 'cn-c3-n07'],
  ['NH4Cl', 'Ammonium chloride', 'salt', 'A sublimable white solid — separated from sand and salt by sublimation.', 'cn-c1-n08'],
  ['(NH4)2SO4', 'Ammonium sulphate', 'salt', 'The book’s atom-counting example: 2 N, 8 H, 1 S and 4 O in one molecule.', 'cn-c5-n05'],
  ['Na2SO4', 'Sodium sulphate', 'salt', 'Reacts with BaCl₂ to give white BaSO₄. Its hydrate is Glauber’s salt.', 'cn-c1-n10'],
  ['BaCl2', 'Barium chloride', 'salt', 'BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl — used to verify the law of conservation of mass.', 'cn-c1-n10'],
  ['BaSO4', 'Barium sulphate', 'salt', 'White precipitate formed in the BaCl₂ + Na₂SO₄ reaction.', 'cn-c6-n07'],
  ['AgCl', 'Silver chloride', 'salt', 'The classic white precipitate.', 'cn-c5-n09'],
  ['AgNO3', 'Silver nitrate', 'salt', 'Copper displaces silver from it, turning the solution blue.', 'cn-c6-n06'],
  ['ZnCl2', 'Zinc chloride', 'salt', 'Formed with hydrogen in the lab method: Zn + 2HCl → ZnCl₂ + H₂.', 'cn-c7-n03'],
  ['ZnSO4', 'Zinc sulphate', 'salt', 'Colourless salt formed when zinc displaces copper from CuSO₄.', 'cn-c6-n06'],
  ['Pb(NO3)2', 'Lead(II) nitrate', 'salt', 'Heating gives PbO, NO₂ and O₂: 2Pb(NO₃)₂ → 2PbO + 4NO₂ + O₂.', 'cn-c6-n05'],
  ['CaCO3', 'Calcium carbonate (marble, chalk, limestone)', 'salt', 'Chalk, limestone and marble are all CaCO₃. Heated at 1000°C it gives CaO + CO₂ (endothermic); dilute HCl on it releases CO₂.', 'cn-c9-n01'],
  ['Na2CO3', 'Sodium carbonate', 'salt', 'Washing soda is its hydrate. Removes permanent hardness from water.', 'cn-c8-n10'],
  ['NaHCO3', 'Sodium hydrogencarbonate (baking soda)', 'salt', 'Baking soda; treats a bee sting (acidic). Used in soda-acid and foam fire extinguishers.', 'cn-c3-n04'],
  ['Ca(HCO3)2', 'Calcium hydrogencarbonate', 'salt', 'Soluble; formed when excess CO₂ clears lime water. Causes temporary hardness (removed by boiling).', 'cn-c9-n09'],
  ['Al2(SO4)3', 'Aluminium sulphate', 'salt', 'With NaHCO₃ it makes the foam extinguisher used for oil fires.', 'cn-c9-n10'],
  ['CaCl2', 'Calcium chloride', 'salt', 'Deliquescent salt; a cause of hard water when dissolved.', 'cn-c8-n08'],
  ['CuSO4', 'Copper(II) sulphate', 'salt', 'Blue in solution, white when anhydrous — anhydrous CuSO₄ turns blue with water (test for water). Zinc turns it colourless.', 'cn-c8-n09'],
  ['FeS', 'Iron(II) sulphide', 'salt', 'Made by heating Fe + S (7 : 4 by mass). Non-magnetic and insoluble in CS₂ — a new substance, so a chemical change.', 'cn-c2-n03'],
  ['CuSO4·5H2O', 'Blue vitriol (copper sulphate crystals)', 'hydrate', 'A hydrate: blue crystals holding 5 molecules of water of crystallisation.', 'cn-c8-n08'],
  ['FeSO4·7H2O', 'Green vitriol (iron(II) sulphate)', 'hydrate', 'Green hydrated crystals.', 'cn-c8-n08'],
  ['MgSO4·7H2O', 'Epsom salt', 'hydrate', 'Hydrated magnesium sulphate.', 'cn-c8-n08'],
  ['Na2CO3·10H2O', 'Washing soda', 'hydrate', 'Efflorescent — loses crystal water to the air.', 'cn-c8-n08'],
  ['Na2SO4·10H2O', 'Glauber’s salt', 'hydrate', 'Hydrated sodium sulphate.', 'cn-c8-n08'],
  ['CH4', 'Methane', 'organic', 'The simplest hydrocarbon (valency of carbon 4); a greenhouse gas and the main part of natural gas.', 'cn-c5-n02'],
  ['C2H5OH', 'Ethanol (alcohol)', 'organic', 'Boils at 78°C; separated from water by fractional distillation. Non-electrolyte; also stops radiator water freezing.', 'cn-c3-n09'],
  ['C6H12O6', 'Glucose', 'organic', 'A sugar; a non-electrolyte.', 'cn-c3-n04'],
  ['C12H22O11', 'Sucrose (sugar)', 'organic', 'Table sugar — dissolves in water but does not conduct electricity.', 'cn-c7-n02'],
  ['CS2', 'Carbon disulphide', 'other', 'Solvent that dissolves sulphur — not iron sulphide.', 'cn-c3-n07'],
  ['CO(NH2)2', 'Urea', 'organic', 'Fertilizer made from CO₂ + NH₃ at 150°C under pressure.', 'cn-c9-n10']
];

// Molecules of elements and allotropes the book names; shown with the elements but not on the table.
const CHEM_BOOK_MOLECULES = [
  ['H2', 'Hydrogen molecule', 'Atomicity 2. Lightest gas.', 'cn-c3-n03'],
  ['O2', 'Oxygen molecule', 'Atomicity 2. Supports burning.', 'cn-c3-n03'],
  ['N2', 'Nitrogen molecule', 'Atomicity 2. Boils at −196°C, before oxygen from liquid air.', 'cn-c3-n09'],
  ['Cl2', 'Chlorine molecule', 'Atomicity 2. Displaces Br₂ and I₂.', 'cn-c6-n06'],
  ['O3', 'Ozone', 'Atomicity 3 — an allotrope of oxygen.', 'cn-c3-n03'],
  ['P4', 'White phosphorus molecule', 'Atomicity 4.', 'cn-c3-n03'],
  ['S8', 'Sulphur molecule', 'Atomicity 8.', 'cn-c3-n03'],
  ['C60', 'Buckminster fullerene', 'Sixty carbon atoms in a sphere — the third crystalline allotrope of carbon, after diamond and graphite.', 'cn-c9-n05']
];
