// ============================================================
// ICSE CLASS 8 CHEMISTRY — ALL 9 CHAPTERS
// Original content written for StudyHub
// ============================================================
const CHEMISTRY_DATA = [

// ======================== CH1: MATTER ========================
{id:"ch1n1",topicId:"chem-ch1",type:"note",subtopic:"Matter and Its States",content:'Matter is anything that has mass and occupies space. It exists in three states: SOLID (fixed shape and volume, particles tightly packed), LIQUID (fixed volume but no fixed shape, particles loosely arranged), GAS (no fixed shape or volume, particles far apart and move freely).',explanation:'Everything around you — your desk, water, air — is matter. The state depends on how strongly particles attract each other and how much energy they have.',teacherTip:'Solid = ice cubes stacked tight. Liquid = water flowing. Gas = steam escaping.',examTip:'Always describe particles arrangement AND intermolecular forces for each state.'},
{id:"ch1n2",topicId:"chem-ch1",type:"note",subtopic:"Interconversion of States",content:'States of matter can change: Melting (solid→liquid at melting point), Boiling (liquid→gas at boiling point), Condensation (gas→liquid on cooling), Freezing (liquid→solid on cooling), Sublimation (solid→gas directly), Deposition (gas→solid). Temperature remains constant during change of state.',explanation:'Adding heat gives particles more energy to break free. Removing heat slows them down so they lock together again.',teacherTip:'Draw the change-of-state cycle as a triangle: Solid ↔ Liquid ↔ Gas, with Sublimation as a shortcut.',examTip:'State that temperature remains CONSTANT during change of state — this is about latent heat.'},
{id:"ch1n3",topicId:"chem-ch1",type:"note",subtopic:"Diffusion",content:'DIFFUSION is the spontaneous mixing of particles of two substances due to their random motion. It occurs in gases (fastest), liquids (slower), and very slowly in solids. Example: smell of perfume spreads across a room.',explanation:'Particles are always moving randomly. When two substances come in contact, their particles intermingle without any stirring needed.',teacherTip:'Diffusion is fastest in gases because gas particles move the fastest and have the most space.',examTip:'Rate of diffusion: Gases > Liquids > Solids. Mention this order for full marks.'},
// T/F
{id:"ch1tf1",topicId:"chem-ch1",type:"true_false",subtopic:"Objective Questions",question:"Gases have a definite shape and volume.",correctAnswer:"false",answer:"False. Gases have NEITHER definite shape NOR definite volume. They expand to fill any container completely.",teacherTip:'Only solids have both definite shape and volume.',examTip:'Solids = both definite. Liquids = definite volume only. Gases = neither.'},
{id:"ch1tf2",topicId:"chem-ch1",type:"true_false",subtopic:"Objective Questions",question:"Diffusion is fastest in gases.",correctAnswer:"true",answer:"True. Gas particles have the most kinetic energy and the largest intermolecular spaces, allowing them to mix the fastest.",teacherTip:'More space + more speed = faster mixing.',examTip:'Compare diffusion rates across all three states when answering.'},
// Fill blanks
{id:"ch1fb1",topicId:"chem-ch1",type:"fill_blank",subtopic:"Objective Questions",question:"The change of a solid directly into gas is called ______.",blankAnswer:"sublimation",answer:"Sublimation. Examples: camphor, dry ice, naphthalene balls.",teacherTip:'Sub-limation = solid "skips" the liquid step.',examTip:'Always give an example substance when mentioning sublimation.'},
// MCQ
{id:"ch1mcq1",topicId:"chem-ch1",type:"mcq",subtopic:"Objective Questions",question:"Which state of matter has maximum intermolecular space?",options:["Solid","Liquid","Gas","Plasma"],correctOption:2,answer:"Gas. Particles in a gas are far apart with negligible attractive forces, which is why gases can be compressed easily.",teacherTip:'More space = easier to compress. Gases are highly compressible.',examTip:'Link intermolecular space to compressibility in your answers.'},
// Short answer
{id:"ch1sa1",topicId:"chem-ch1",type:"short_answer",subtopic:"Short/Long Answer",question:"Compare solids, liquids, and gases based on shape, volume, compressibility, and particle arrangement.",answer:'SOLIDS: Definite shape, definite volume, incompressible, particles tightly packed vibrating in fixed positions.\n\nLIQUIDS: No definite shape (takes container shape), definite volume, slightly compressible, particles close but can slide past each other.\n\nGASES: No definite shape or volume, highly compressible, particles far apart moving randomly at high speed.',teacherTip:'Make a 4-column table: Property | Solid | Liquid | Gas.',examTip:'Compare at least 4 properties for maximum marks.'},

// ======================== CH2: PHYSICAL AND CHEMICAL CHANGES ========================
{id:"ch2n1",topicId:"chem-ch2",type:"note",subtopic:"Physical vs Chemical Changes",content:'PHYSICAL CHANGE: Change in physical properties (shape, size, state) without forming new substance. Reversible. No change in chemical composition. Examples: melting ice, dissolving sugar, breaking glass.\nCHEMICAL CHANGE: New substance formed with different properties. Usually irreversible. Involves energy change. Examples: rusting iron, burning wood, cooking food.',explanation:'Tearing paper is physical (still paper). Burning paper is chemical (becomes ash + CO₂ — completely new substances).',teacherTip:'Physical = same substance, different look. Chemical = different substance entirely.',examTip:'Give at least 4 differences with examples of each type.'},
{id:"ch2n2",topicId:"chem-ch2",type:"note",subtopic:"Signs of Chemical Change",content:'How to identify a chemical change: (1) Change in colour (iron turning brown/rusty), (2) Evolution of gas (bubbles when vinegar meets baking soda), (3) Change in temperature (exothermic/endothermic), (4) Formation of precipitate (insoluble solid), (5) Change in smell (milk turning sour).',explanation:'If you see bubbling, colour change, heat release, or a new smell — a chemical reaction is probably happening.',teacherTip:'Remember: "Colour, Gas, Heat, Precipitate, Smell" — the 5 signs.',examTip:'List at least 3 signs with examples when identifying a chemical change.'},
// T/F
{id:"ch2tf1",topicId:"chem-ch2",type:"true_false",subtopic:"Objective Questions",question:"Melting of ice is a chemical change.",correctAnswer:"false",answer:"False. Melting of ice is a PHYSICAL change. Water changes state (solid→liquid) but its chemical composition (H₂O) remains the same. It is also reversible.",teacherTip:'Change of state = physical change. Always.',examTip:'Mention "no new substance formed" and "reversible" when explaining physical changes.'},
{id:"ch2tf2",topicId:"chem-ch2",type:"true_false",subtopic:"Objective Questions",question:"Rusting of iron is an irreversible chemical change.",correctAnswer:"true",answer:"True. Iron reacts with oxygen and moisture to form iron oxide (rust) — a completely new substance. This cannot be easily reversed.",teacherTip:'Rust = Fe₂O₃ (iron oxide). Completely different from iron.',examTip:'Name the product (iron oxide) to show deeper understanding.'},
// MCQ
{id:"ch2mcq1",topicId:"chem-ch2",type:"mcq",subtopic:"Objective Questions",question:"Which of the following is a chemical change?",options:["Dissolving sugar in water","Tearing paper","Burning magnesium ribbon","Melting butter"],correctOption:2,answer:"Burning magnesium ribbon produces magnesium oxide (white ash) — a completely new substance with different properties. The other options are physical changes.",teacherTip:'Burning almost always = chemical change (new substances form).',examTip:'"Burning" and "rusting" are the most common chemical change examples in exams.'},
// Short answer
{id:"ch2sa1",topicId:"chem-ch2",type:"short_answer",subtopic:"Short/Long Answer",question:"Differentiate between physical and chemical changes. Give three examples of each.",answer:'PHYSICAL CHANGE:\n• No new substance formed\n• Usually reversible\n• No change in chemical composition\n• Examples: melting ice, dissolving salt, breaking a plate\n\nCHEMICAL CHANGE:\n• New substance with different properties is formed\n• Usually irreversible\n• Chemical composition changes\n• Examples: burning wood, rusting iron, cooking an egg',teacherTip:'The key question: "Is a NEW substance formed?" Yes = chemical. No = physical.',examTip:'Compare at least 4 features and give 3 examples of each for full marks.'},

// ======================== CH3: ELEMENTS, COMPOUNDS AND MIXTURES ========================
{id:"ch3n1",topicId:"chem-ch3",type:"note",subtopic:"Elements, Compounds, Mixtures",content:'ELEMENT: Pure substance made of only one type of atom. Cannot be broken down further. Examples: Iron (Fe), Oxygen (O₂), Gold (Au). ~118 known elements.\nCOMPOUND: Pure substance made of two or more elements chemically combined in a fixed ratio. Examples: Water (H₂O), Salt (NaCl), CO₂.\nMIXTURE: Two or more substances physically mixed, NOT chemically combined. No fixed ratio. Examples: air, salt water, salad.',explanation:'Elements are like individual Lego colours. Compounds are specific Lego models (fixed design). Mixtures are random piles of Lego.',teacherTip:'Element = 1 type of atom. Compound = atoms chemically joined. Mixture = just physically mixed.',examTip:'Key difference: Compounds have fixed ratio and chemical bonding. Mixtures don\'t.'},
{id:"ch3n2",topicId:"chem-ch3",type:"note",subtopic:"Types of Mixtures",content:'HOMOGENEOUS MIXTURE (solution): Uniform composition throughout. Cannot see separate components. Examples: salt water, air, alloys (brass). HETEROGENEOUS MIXTURE: Non-uniform composition. Can see separate components. Examples: sand+water, oil+water, salad.',explanation:'In a homogeneous mixture, every sip of salt water tastes the same. In a heterogeneous mixture, you can pick out the individual parts.',teacherTip:'Homo = same throughout. Hetero = different parts visible.',examTip:'Air is a homogeneous mixture (not a compound!) — a very common exam trick.'},
{id:"ch3n3",topicId:"chem-ch3",type:"note",subtopic:"Separation of Mixtures",content:'Methods to separate mixtures: (1) FILTRATION — separates insoluble solid from liquid (sand from water). (2) EVAPORATION — gets dissolved solid from solution (salt from salt water). (3) DISTILLATION — separates liquids with different boiling points. (4) MAGNETIC SEPARATION — separates magnetic substances (iron from sand). (5) CHROMATOGRAPHY — separates colours/dyes in a mixture.',explanation:'Each method exploits a physical property difference between components — size (filtration), boiling point (distillation), magnetism, etc.',teacherTip:'Match the method to the property: Filtration=size, Distillation=boiling point, Magnetic=magnetism.',examTip:'Name the PROPERTY being used when describing each separation method.'},
// T/F
{id:"ch3tf1",topicId:"chem-ch3",type:"true_false",subtopic:"Objective Questions",question:"Air is a compound.",correctAnswer:"false",answer:"False. Air is a MIXTURE of gases (78% nitrogen, 21% oxygen, 1% other gases). Components are not chemically bonded and can be separated physically.",teacherTip:'Air = mixture. Water = compound. Don\'t confuse them!',examTip:'Air has variable composition (humidity changes) — compounds have fixed composition.'},
{id:"ch3tf2",topicId:"chem-ch3",type:"true_false",subtopic:"Objective Questions",question:"A compound can be separated into its elements by physical methods.",correctAnswer:"false",answer:"False. Compounds can only be broken into elements by CHEMICAL methods (like electrolysis). Mixtures are separated by physical methods.",teacherTip:'Physical separation = mixtures. Chemical separation = compounds.',examTip:'Electrolysis of water (H₂O → H₂ + O₂) is a classic example of chemical separation.'},
// Fill blanks
{id:"ch3fb1",topicId:"chem-ch3",type:"fill_blank",subtopic:"Objective Questions",question:"A mixture with uniform composition throughout is called a ______ mixture.",blankAnswer:"homogeneous",answer:"Homogeneous mixture (also called a solution). Every part has the same composition.",teacherTip:'Homo = same. Homogeneous = same throughout.',examTip:'Give an example (salt water, air) alongside the term.'},
// MCQ
{id:"ch3mcq1",topicId:"chem-ch3",type:"mcq",subtopic:"Objective Questions",question:"Which method is used to separate salt from sea water?",options:["Filtration","Evaporation","Magnetic separation","Decantation"],correctOption:1,answer:"Evaporation. When sea water is heated, water evaporates leaving behind solid salt crystals.",teacherTip:'Salt is dissolved (not suspended), so filtration won\'t work — evaporation is needed.',examTip:'Filtration = insoluble solids. Evaporation = dissolved solids.'},
// Short answer
{id:"ch3sa1",topicId:"chem-ch3",type:"short_answer",subtopic:"Short/Long Answer",question:"Differentiate between elements, compounds, and mixtures with examples.",answer:'ELEMENT: Made of one type of atom. Cannot be decomposed. Examples: Iron (Fe), Oxygen (O₂), Carbon (C).\n\nCOMPOUND: Two or more elements chemically combined in fixed ratio. Properties differ from constituent elements. Examples: Water (H₂O), Carbon dioxide (CO₂).\n\nMIXTURE: Two or more substances physically mixed in any ratio. Each retains its properties. Separated by physical methods. Examples: Air, salt water, sand+iron filings.',teacherTip:'Element=simplest. Compound=chemically joined. Mixture=physically mixed.',examTip:'Mention "fixed ratio" for compounds and "any ratio" for mixtures — key distinction.'},

// ======================== CH4: ATOMIC STRUCTURE ========================
{id:"ch4n1",topicId:"chem-ch4",type:"note",subtopic:"Structure of an Atom",content:'An atom has three subatomic particles: (1) PROTONS — positive charge (+1), found in nucleus, mass ≈ 1 amu. (2) NEUTRONS — no charge (neutral), found in nucleus, mass ≈ 1 amu. (3) ELECTRONS — negative charge (-1), orbit the nucleus in shells/energy levels, negligible mass.\nAtomic number (Z) = number of protons. Mass number (A) = protons + neutrons.',explanation:'The nucleus (centre) contains protons and neutrons — it\'s tiny but holds almost all the mass. Electrons whiz around in shells at great speed.',teacherTip:'Protons = Positive = in the Plus centre. Electrons = nEgative = outside.',examTip:'Atoms are neutral: number of protons = number of electrons.'},
{id:"ch4n2",topicId:"chem-ch4",type:"note",subtopic:"Electron Shells and Valency",content:'Electrons are arranged in shells (K, L, M, N...). Maximum electrons per shell: K=2, L=8, M=8 (for first 20 elements), N=2. The outermost shell electrons are called VALENCE ELECTRONS. VALENCY = combining capacity of an atom = electrons needed to complete the outermost shell (octet rule: atoms want 8 electrons in outer shell, except K which wants 2).',explanation:'Sodium has 2,8,1 arrangement. It has 1 valence electron and easily loses it, so valency = 1. Chlorine has 2,8,7 — needs 1 more electron, so valency = 1.',teacherTip:'Shell capacity: 2, 8, 8, 2 (for first 20). Just memorize this!',examTip:'Draw electron diagrams (dot-cross) for at least 5 common elements.'},
{id:"ch4n3",topicId:"chem-ch4",type:"note",subtopic:"Isotopes and Isobars",content:'ISOTOPES: Atoms of the SAME element with same atomic number but DIFFERENT mass numbers (different neutrons). Example: Carbon-12 and Carbon-14 (both have 6 protons, but 6 vs 8 neutrons).\nISOBARS: Atoms of DIFFERENT elements with same mass number but different atomic numbers. Example: ⁴⁰Ar and ⁴⁰Ca.',explanation:'Isotopes are like siblings — same family (element) but different weight. Isobars are like strangers who happen to weigh the same.',teacherTip:'Iso-TOPE = same Place (same element, same Z). Iso-BAR = same Bar (same mass A).',examTip:'Know at least 2 examples of isotopes (C-12/C-14, H-1/H-2/H-3).'},
// T/F
{id:"ch4tf1",topicId:"chem-ch4",type:"true_false",subtopic:"Objective Questions",question:"Neutrons have a negative charge.",correctAnswer:"false",answer:"False. Neutrons have NO charge (they are neutral). Electrons have negative charge, and protons have positive charge.",teacherTip:'Neutron = Neutral. The name gives it away!',examTip:'Proton = +1, Electron = -1, Neutron = 0. Memorize charges.'},
{id:"ch4tf2",topicId:"chem-ch4",type:"true_false",subtopic:"Objective Questions",question:"The maximum number of electrons in the second shell (L) is 8.",correctAnswer:"true",answer:"True. The L shell can hold a maximum of 8 electrons. Shell capacity follows 2n² rule (n=shell number): K=2, L=8, M=18 (but 8 for first 20 elements).",teacherTip:'For Class 8: K=2, L=8, M=8 is sufficient.',examTip:'Use 2n² formula if asked to calculate: n=1→2, n=2→8, n=3→18.'},
// Fill blanks
{id:"ch4fb1",topicId:"chem-ch4",type:"fill_blank",subtopic:"Objective Questions",question:"The number of protons in an atom is called its ______.",blankAnswer:"atomic number",answer:"Atomic number (Z) = number of protons. It defines which element an atom belongs to.",teacherTip:'Change the protons = change the element. Atomic number is the element\'s identity.',examTip:'Atomic number = protons = electrons (in a neutral atom).'},
// MCQ
{id:"ch4mcq1",topicId:"chem-ch4",type:"mcq",subtopic:"Objective Questions",question:"Isotopes have the same:",options:["Mass number","Number of neutrons","Atomic number","None of the above"],correctOption:2,answer:"Isotopes have the same atomic number (same number of protons, same element) but different mass numbers (different neutrons).",teacherTip:'Same element = same protons = same atomic number.',examTip:'Isotopes differ ONLY in neutron count.'},
// Short answer
{id:"ch4sa1",topicId:"chem-ch4",type:"short_answer",subtopic:"Short/Long Answer",question:"Draw the atomic structure of Sodium (Na, Z=11, A=23). State its valency.",answer:'Sodium (Na): Atomic number = 11, Mass number = 23\nProtons = 11, Neutrons = 23-11 = 12, Electrons = 11\n\nElectron arrangement: K(2), L(8), M(1)\n\nValency = 1 (it has 1 electron in outermost shell, which it can easily lose to achieve stable configuration of 2,8)\n\nSodium is a metal and forms Na⁺ ion by losing 1 electron.',teacherTip:'Always calculate: Neutrons = Mass number - Atomic number.',examTip:'Show the electron configuration AND state the valency with reasoning.'},

// ======================== CH5: LANGUAGE OF CHEMISTRY ========================
{id:"ch5n1",topicId:"chem-ch5",type:"note",subtopic:"Symbols, Formulae, Equations",content:'CHEMICAL SYMBOL: Short abbreviation for an element (1 or 2 letters, first always capital). Examples: H (Hydrogen), Na (Sodium), Fe (Iron).\nCHEMICAL FORMULA: Shows types and numbers of atoms in a compound using symbols and subscripts. H₂O = 2 hydrogen + 1 oxygen.\nCHEMICAL EQUATION: Represents a chemical reaction using formulae. Reactants → Products. Must be BALANCED (same atoms on both sides).',explanation:'Symbols are like abbreviations (Dr. for Doctor). Formulae are like molecular recipes. Equations are like cooking instructions showing what goes in and what comes out.',teacherTip:'Na comes from Latin "Natrium", Fe from "Ferrum", K from "Kalium" — learn Latin origins!',examTip:'Know symbols for all common elements, especially those from Latin names.'},
{id:"ch5n2",topicId:"chem-ch5",type:"note",subtopic:"Balancing Chemical Equations",content:'A balanced equation has equal numbers of each type of atom on both sides (Law of Conservation of Mass — matter cannot be created or destroyed). Steps: (1) Write word equation, (2) Write unbalanced equation with formulae, (3) Count atoms on each side, (4) Add coefficients to balance. Example: 2H₂ + O₂ → 2H₂O.',explanation:'If you start with 4 hydrogen atoms and 2 oxygen atoms, you must end with 4 hydrogen and 2 oxygen. Nothing disappears!',teacherTip:'Never change subscripts to balance! Only change coefficients (numbers in front).',examTip:'Always verify your balanced equation by counting atoms on both sides.'},
// T/F
{id:"ch5tf1",topicId:"chem-ch5",type:"true_false",subtopic:"Objective Questions",question:"The symbol for Sodium is So.",correctAnswer:"false",answer:"False. The symbol for Sodium is Na (from its Latin name Natrium). Chemical symbols use either 1 or 2 letters, with the first always capitalized.",teacherTip:'Na = Natrium (Latin for Sodium). Many metals have Latin-derived symbols.',examTip:'Common Latin symbols: Na (Sodium), K (Potassium), Fe (Iron), Cu (Copper), Ag (Silver), Au (Gold).'},
// Fill blanks
{id:"ch5fb1",topicId:"chem-ch5",type:"fill_blank",subtopic:"Objective Questions",question:"The formula of water is ______.",blankAnswer:"H₂O",answer:"H₂O — each water molecule contains 2 hydrogen atoms and 1 oxygen atom.",teacherTip:'The subscript 2 means 2 atoms of hydrogen. No subscript = 1 atom.',examTip:'Know formulae of common compounds: H₂O, CO₂, NaCl, HCl, H₂SO₄, NaOH.'},
// MCQ
{id:"ch5mcq1",topicId:"chem-ch5",type:"mcq",subtopic:"Objective Questions",question:"In a balanced equation, what is conserved?",options:["Colour","Volume","Mass (number of atoms)","Temperature"],correctOption:2,answer:"Mass is conserved (Law of Conservation of Mass). The total number of atoms of each element must be the same on both sides of the equation.",teacherTip:'Atoms are rearranged, not created or destroyed.',examTip:'Name the law: "Law of Conservation of Mass" for extra marks.'},
// Short answer
{id:"ch5sa1",topicId:"chem-ch5",type:"short_answer",subtopic:"Short/Long Answer",question:"Balance the following equation: Fe + O₂ → Fe₂O₃",answer:'Step 1: Count atoms\nLeft: Fe=1, O=2 | Right: Fe=2, O=3\n\nStep 2: Balance Fe by putting 2 in front of Fe:\n2Fe + O₂ → Fe₂O₃ (Fe balanced, but O still unbalanced)\n\nStep 3: To balance O, we need 3 on left. Use LCM of 2 and 3 = 6:\n4Fe + 3O₂ → 2Fe₂O₃\n\nCheck: Left: Fe=4, O=6 | Right: Fe=4, O=6 ✓\n\nBalanced equation: 4Fe + 3O₂ → 2Fe₂O₃',teacherTip:'Find the LCM when oxygen atoms don\'t balance easily.',examTip:'Always show the verification step (counting atoms on both sides).'},

// ======================== CH6: CHEMICAL REACTIONS ========================
{id:"ch6n1",topicId:"chem-ch6",type:"note",subtopic:"Types of Chemical Reactions",content:'(1) COMBINATION (Synthesis): A + B → AB. Two substances combine. Example: 2Mg + O₂ → 2MgO.\n(2) DECOMPOSITION: AB → A + B. One substance breaks down. Example: 2H₂O → 2H₂ + O₂ (electrolysis).\n(3) DISPLACEMENT: A + BC → AC + B. More reactive element replaces less reactive. Example: Zn + CuSO₄ → ZnSO₄ + Cu.\n(4) DOUBLE DISPLACEMENT: AB + CD → AD + CB. Exchange of ions. Example: NaCl + AgNO₃ → AgCl↓ + NaNO₃.',explanation:'Combination = marriage. Decomposition = divorce. Displacement = replacement. Double displacement = partner swap.',teacherTip:'Learn one example for each type — they always ask for examples.',examTip:'Identify reaction type by pattern: 2→1 (combination), 1→2 (decomposition), etc.'},
{id:"ch6n2",topicId:"chem-ch6",type:"note",subtopic:"Reactivity Series",content:'The REACTIVITY SERIES ranks metals from most reactive to least reactive: K > Na > Ca > Mg > Al > Zn > Fe > Pb > H > Cu > Ag > Au > Pt. A more reactive metal can displace a less reactive metal from its salt solution.',explanation:'Potassium is like an overexcited kid — it reacts violently with almost everything. Gold is calm and barely reacts with anything, which is why it doesn\'t tarnish.',teacherTip:'Mnemonic: "Please Stop Calling Me A Zebra, I Like Hunting Cute Silver Gold Pets."',examTip:'Know at least the top 8 metals in order. H is included to predict acid reactions.'},
// T/F
{id:"ch6tf1",topicId:"chem-ch6",type:"true_false",subtopic:"Objective Questions",question:"A more reactive metal can displace a less reactive metal from its salt solution.",correctAnswer:"true",answer:"True. For example, zinc (more reactive) displaces copper (less reactive) from copper sulphate solution: Zn + CuSO₄ → ZnSO₄ + Cu.",teacherTip:'The bully (more reactive) kicks out the weaker one (less reactive).',examTip:'Give a specific example with equation when explaining displacement.'},
// MCQ
{id:"ch6mcq1",topicId:"chem-ch6",type:"mcq",subtopic:"Objective Questions",question:"2Mg + O₂ → 2MgO is an example of:",options:["Decomposition","Displacement","Combination","Double displacement"],correctOption:2,answer:"Combination reaction — two reactants (Mg and O₂) combine to form one product (MgO).",teacherTip:'Two things → one thing = combination. One thing → two things = decomposition.',examTip:'Count reactants and products to identify the type quickly.'},
// Short answer
{id:"ch6sa1",topicId:"chem-ch6",type:"short_answer",subtopic:"Short/Long Answer",question:"Explain the four types of chemical reactions with one example each.",answer:'1. COMBINATION: Two or more substances combine to form one product.\n   2Na + Cl₂ → 2NaCl\n\n2. DECOMPOSITION: One substance breaks into two or more products.\n   2H₂O --electrolysis→ 2H₂ + O₂\n\n3. DISPLACEMENT: A more reactive element replaces a less reactive one.\n   Fe + CuSO₄ → FeSO₄ + Cu\n\n4. DOUBLE DISPLACEMENT: Two compounds exchange ions to form two new compounds.\n   NaCl + AgNO₃ → AgCl↓ + NaNO₃',teacherTip:'Pattern: Combination (A+B→AB), Decomposition (AB→A+B), Displacement (A+BC→AC+B), Double (AB+CD→AD+CB).',examTip:'Write balanced equations for each type to score full marks.'},

// ======================== CH7: HYDROGEN ========================
{id:"ch7n1",topicId:"chem-ch7",type:"note",subtopic:"Hydrogen — Properties & Preparation",content:'HYDROGEN (H₂): Lightest element, colourless, odourless, tasteless gas. Highly inflammable. Burns with a blue flame. Prepared in lab by reacting zinc with dilute hydrochloric acid: Zn + 2HCl → ZnCl₂ + H₂↑. Collected by downward displacement of water (insoluble) or upward displacement of air (lighter than air).',explanation:'Hydrogen is the simplest and lightest of all elements. Its name means "water-former" because burning hydrogen produces water.',teacherTip:'"Hydro" = water, "gen" = producer. Hydrogen literally makes water when burned.',examTip:'Write the lab preparation equation AND the collection method.'},
{id:"ch7n2",topicId:"chem-ch7",type:"note",subtopic:"Uses of Hydrogen",content:'Uses: (1) Fuel — hydrogen fuel cells for clean energy (product is only water). (2) Hydrogenation — converting vegetable oils to ghee/margarine. (3) Manufacturing ammonia (Haber process: N₂ + 3H₂ → 2NH₃). (4) Filling weather balloons (light but now replaced by helium for safety). (5) Rocket fuel (liquid hydrogen).',explanation:'Hydrogen is the fuel of the future — when it burns, the only waste product is water. No pollution!',teacherTip:'Hydrogen fuel cells: 2H₂ + O₂ → 2H₂O + energy. Clean and green!',examTip:'List at least 4 uses with brief explanations.'},
// T/F
{id:"ch7tf1",topicId:"chem-ch7",type:"true_false",subtopic:"Objective Questions",question:"Hydrogen is heavier than air.",correctAnswer:"false",answer:"False. Hydrogen is the LIGHTEST gas — about 14.5 times lighter than air. This is why it can be collected by upward displacement of air.",teacherTip:'Lightest element in the universe! That\'s why it rises up.',examTip:'Mention "upward displacement of air" as the collection method linked to its low density.'},
// MCQ
{id:"ch7mcq1",topicId:"chem-ch7",type:"mcq",subtopic:"Objective Questions",question:"Hydrogen is prepared in the lab by reacting zinc with:",options:["Water","Dilute HCl","Sodium hydroxide","Oxygen"],correctOption:1,answer:"Zinc + dilute hydrochloric acid → Zinc chloride + Hydrogen. Zn + 2HCl → ZnCl₂ + H₂↑",teacherTip:'Zinc + acid = salt + hydrogen. Classic metal-acid reaction!',examTip:'Write the balanced equation with state symbols if possible.'},
// Short answer
{id:"ch7sa1",topicId:"chem-ch7",type:"short_answer",subtopic:"Short/Long Answer",question:"Describe the laboratory preparation of hydrogen gas. How is it collected?",answer:'PREPARATION: Zinc granules are taken in a flask. Dilute hydrochloric acid (HCl) is added through a thistle funnel.\n\nReaction: Zn + 2HCl → ZnCl₂ + H₂↑\n\nCOLLECTION: Hydrogen is collected by:\n1. Downward displacement of water — because H₂ is insoluble in water\n2. Upward displacement of air — because H₂ is lighter than air\n\nTEST: Bring a burning splint near the gas. Hydrogen burns with a "pop" sound.',teacherTip:'The "pop" test is the standard test for hydrogen gas.',examTip:'Describe apparatus, reaction, collection AND test for complete answer.'},

// ======================== CH8: WATER ========================
{id:"ch8n1",topicId:"chem-ch8",type:"note",subtopic:"Water — Properties and Composition",content:'Water (H₂O) is a compound of hydrogen and oxygen in 2:1 ratio by volume. It is a UNIVERSAL SOLVENT (dissolves most substances). Boiling point = 100°C, Freezing point = 0°C. Anomalous expansion: water expands on freezing (ice floats). Water exists in all 3 states in nature.',explanation:'Water is called the universal solvent because it dissolves more substances than any other liquid. This is essential for life — nutrients dissolve in water to reach cells.',teacherTip:'Water\'s anomalous expansion is why ice floats — this is crucial for aquatic life in cold climates.',examTip:'Explain WHY ice floating is important (protects aquatic life underneath).'},
{id:"ch8n2",topicId:"chem-ch8",type:"note",subtopic:"Hard and Soft Water",content:'SOFT WATER: Lathers easily with soap. Contains no dissolved calcium/magnesium salts. Example: rainwater, distilled water.\nHARD WATER: Does not lather easily with soap, forms scum. Contains dissolved Ca²⁺ or Mg²⁺ salts.\nTemporary hardness: Caused by bicarbonates Ca(HCO₃)₂. Removed by boiling.\nPermanent hardness: Caused by sulphates/chlorides (CaSO₄, MgCl₂). Removed by adding washing soda (Na₂CO₃).',explanation:'Hard water wastes soap because calcium and magnesium react with soap to form insoluble scum instead of lather.',teacherTip:'Temporary = boiling fixes it. Permanent = needs chemicals (washing soda).',examTip:'Know the difference between temporary and permanent hardness AND how to remove each.'},
{id:"ch8n3",topicId:"chem-ch8",type:"note",subtopic:"Water Purification",content:'Methods of water purification: (1) FILTRATION — removes suspended impurities. (2) CHLORINATION — adding chlorine to kill germs. (3) BOILING — kills bacteria and viruses (simplest method). (4) DISTILLATION — evaporation + condensation gives purest water. (5) RO (Reverse Osmosis) — forces water through membrane to remove dissolved salts.',explanation:'Each method targets different impurities. Often multiple methods are used together for safe drinking water.',teacherTip:'Distilled water is the purest form but tasteless (no minerals).',examTip:'Name at least 3 methods with what each removes.'},
// T/F
{id:"ch8tf1",topicId:"chem-ch8",type:"true_false",subtopic:"Objective Questions",question:"Hard water lathers easily with soap.",correctAnswer:"false",answer:"False. SOFT water lathers easily. Hard water does NOT lather because dissolved calcium/magnesium ions react with soap to form insoluble scum.",teacherTip:'Hard water = hard to lather. The name is a clue!',examTip:'Explain the chemistry: Ca²⁺/Mg²⁺ + soap → scum (insoluble).'},
// Fill blanks
{id:"ch8fb1",topicId:"chem-ch8",type:"fill_blank",subtopic:"Objective Questions",question:"Temporary hardness of water is caused by ______ salts.",blankAnswer:"bicarbonate",answer:"Temporary hardness is caused by dissolved bicarbonates of calcium and magnesium — Ca(HCO₃)₂ and Mg(HCO₃)₂. Removed by boiling.",teacherTip:'Bicarbonate = temporary. Sulphate/chloride = permanent.',examTip:'Write the formula Ca(HCO₃)₂ for precision.'},
// MCQ
{id:"ch8mcq1",topicId:"chem-ch8",type:"mcq",subtopic:"Objective Questions",question:"Which method gives the purest form of water?",options:["Filtration","Boiling","Chlorination","Distillation"],correctOption:3,answer:"Distillation gives the purest water by evaporating and re-condensing. It removes dissolved salts, germs, and all impurities.",teacherTip:'Distilled water = lab-grade pure. Used in batteries and experiments.',examTip:'Mention that distilled water removes BOTH suspended AND dissolved impurities.'},
// Short answer
{id:"ch8sa1",topicId:"chem-ch8",type:"short_answer",subtopic:"Short/Long Answer",question:"Differentiate between hard water and soft water. How can hardness be removed?",answer:'SOFT WATER: Lathers easily with soap. Free from Ca²⁺/Mg²⁺ salts. Example: rainwater, distilled water.\n\nHARD WATER: Does not lather, forms scum with soap. Contains dissolved Ca²⁺ or Mg²⁺ salts.\n\nRemoving hardness:\n1. TEMPORARY HARDNESS (bicarbonates): Removed by boiling — bicarbonates decompose into insoluble carbonates that settle down.\n2. PERMANENT HARDNESS (sulphates/chlorides): Removed by adding washing soda (Na₂CO₃) — converts soluble Ca/Mg salts into insoluble carbonates.',teacherTip:'Boiling works for temporary only. Washing soda works for both types.',examTip:'Name the specific salts causing each type of hardness for complete answers.'},

// ======================== CH9: CARBON AND ITS COMPOUNDS ========================
{id:"ch9n1",topicId:"chem-ch9",type:"note",subtopic:"Carbon — Allotropes",content:'Carbon exists in different forms called ALLOTROPES — same element, different structures:\n(1) DIAMOND — hardest natural substance, transparent, each C bonded to 4 others in 3D network. Used in cutting/jewellery.\n(2) GRAPHITE — soft, black, slippery. Each C bonded to 3 others in layers. Good conductor. Used in pencils, lubricants.\n(3) FULLERENE (Buckminsterfullerene C₆₀) — cage-like spherical structure.\nAll allotropes are pure carbon but have vastly different properties.',explanation:'Diamond and graphite are both 100% carbon, yet one is the hardest substance and the other is one of the softest. The difference is how atoms are arranged!',teacherTip:'Same atoms, different arrangement = different properties. That\'s the magic of allotropy.',examTip:'Compare diamond and graphite in at least 4 properties (hardness, conductivity, structure, uses).'},
{id:"ch9n2",topicId:"chem-ch9",type:"note",subtopic:"Carbon Compounds",content:'Carbon forms a huge number of compounds because it has valency 4 (can form 4 bonds) and can bond with itself (catenation). Key carbon compounds:\n(1) CO₂ (Carbon dioxide) — exhaled by animals, used by plants, greenhouse gas.\n(2) CO (Carbon monoxide) — poisonous, colourless, odourless. From incomplete combustion.\n(3) CH₄ (Methane) — simplest hydrocarbon, main component of natural gas.\n(4) C₂H₅OH (Ethanol) — alcohol in drinks, also a fuel.',explanation:'Carbon is the "Lego king" of chemistry — its ability to form 4 bonds and chain with itself means it can build millions of different molecules.',teacherTip:'Catenation = Carbon chaining with itself. This is why organic chemistry is so vast.',examTip:'Know the formula, properties, and one use for CO₂, CO, and CH₄.'},
{id:"ch9n3",topicId:"chem-ch9",type:"note",subtopic:"CO₂ — Properties and Test",content:'Carbon dioxide (CO₂): Colourless, odourless gas. Heavier than air. Does not support combustion (extinguishes fire). Turns lime water milky (test for CO₂): CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O. Produced by: burning fuels, respiration, fermentation. Used in: fire extinguishers, carbonated drinks, photosynthesis.',explanation:'CO₂ is like a fire blanket — it smothers flames because it doesn\'t support burning. The lime water test is the definitive chemical test for CO₂.',teacherTip:'Lime water test: Clear → Milky = CO₂ is present. Write the equation!',examTip:'The lime water test equation is one of the most asked equations in chemistry.'},
// T/F
{id:"ch9tf1",topicId:"chem-ch9",type:"true_false",subtopic:"Objective Questions",question:"Diamond and graphite are allotropes of carbon.",correctAnswer:"true",answer:"True. Both are made entirely of carbon atoms but have different structural arrangements, giving them vastly different physical properties.",teacherTip:'Allotropes = same element, different forms. Like carbon wearing different outfits.',examTip:'Name at least 3 differences between diamond and graphite when discussing allotropy.'},
{id:"ch9tf2",topicId:"chem-ch9",type:"true_false",subtopic:"Objective Questions",question:"Carbon dioxide supports combustion.",correctAnswer:"false",answer:"False. CO₂ does NOT support combustion. It extinguishes fire, which is why it is used in fire extinguishers.",teacherTip:'CO₂ = fire killer. That\'s its superpower in fire extinguishers.',examTip:'Mention that CO₂ is denser than air, so it settles over fire and cuts off oxygen.'},
// Fill blanks
{id:"ch9fb1",topicId:"chem-ch9",type:"fill_blank",subtopic:"Objective Questions",question:"Carbon dioxide turns lime water ______.",blankAnswer:"milky",answer:"CO₂ + Ca(OH)₂ → CaCO₃↓ (white precipitate) + H₂O. The insoluble calcium carbonate makes lime water appear milky/cloudy.",teacherTip:'Milky = white precipitate of CaCO₃ suspended in water.',examTip:'Write the full equation — it\'s almost always asked alongside this fact.'},
// MCQ
{id:"ch9mcq1",topicId:"chem-ch9",type:"mcq",subtopic:"Objective Questions",question:"Which allotrope of carbon is the hardest natural substance?",options:["Graphite","Fullerene","Diamond","Charcoal"],correctOption:2,answer:"Diamond — each carbon atom is bonded to 4 others in a rigid 3D tetrahedral network, making it extremely hard.",teacherTip:'4 bonds per carbon in all directions = unbreakable network = hardest.',examTip:'Explain the structural reason (3D tetrahedral bonding) for diamond\'s hardness.'},
// Short answer
{id:"ch9sa1",topicId:"chem-ch9",type:"short_answer",subtopic:"Short/Long Answer",question:"Compare diamond and graphite. Why do they have such different properties despite being the same element?",answer:'Both diamond and graphite are allotropes of carbon (100% carbon), but differ in structure:\n\nDIAMOND:\n• Each C bonded to 4 others (tetrahedral)\n• 3D rigid network structure\n• Hardest natural substance\n• Does not conduct electricity\n• Transparent, lustrous\n• Used in cutting tools, jewellery\n\nGRAPHITE:\n• Each C bonded to 3 others (hexagonal layers)\n• Layers slide over each other (soft, slippery)\n• Good conductor of electricity (free electrons between layers)\n• Black, opaque\n• Used in pencils, lubricants, electrodes\n\nReason for different properties: The ARRANGEMENT of carbon atoms is different, even though the atoms themselves are identical.',teacherTip:'Structure determines properties. Same atoms ≠ same properties if arranged differently.',examTip:'Compare at least 5 properties AND explain the structural reason.'},
];
