// ============================================================
// ICSE CLASS 8 GEOGRAPHY — Starter content (8 chapters)
// Original content written for StudyHub. Expand using "Add New".
// Variable: GEOGRAPHY_DATA  (merged in app.js)
// ============================================================
const GEOGRAPHY_DATA = [
// ===================== CH 1: REPRESENTING THE EARTH =====================
{id:"geo-c1n1",topicId:"geo-ch1",type:"note",subtopic:"Globe vs Map",
 content:'A GLOBE is a true, three-dimensional model of the Earth, while a MAP is a flat (two-dimensional) representation of the whole Earth or a part of it drawn to scale.',
 explanation:'A globe shows shapes and sizes accurately but cannot be carried easily or show small areas in detail. A map is portable and can zoom into a city or street, but flattening a round Earth always causes some distortion.',
 teacherTip:'Globe = "Genuine" shape; Map = "Movable" and detailed.',
 examTip:'List one merit and one demerit of both globe and map for a 2-mark answer.'},
{id:"geo-c1n2",topicId:"geo-ch1",type:"note",subtopic:"Scale of a Map",
 content:'SCALE is the ratio between the distance on a map and the actual distance on the ground. It can be shown as a Statement, a Representative Fraction (R.F.) or a Linear (graphical) scale.',
 explanation:'If 1 cm on a map equals 1 km on the ground, the map is "to scale". R.F. writes this as a fraction like 1:100000, with no units, so it works in any measurement system.',
 teacherTip:'R.F. has the SAME units on both sides, so it has NO units.',
 examTip:'Large-scale maps show small areas in great detail; small-scale maps show large areas with less detail.'},
{id:"geo-c1n3",topicId:"geo-ch1",type:"note",subtopic:"Latitudes & Longitudes",
 content:'LATITUDES are imaginary lines running east-west, parallel to the Equator (0°). LONGITUDES (meridians) run north-south from pole to pole, measured from the Prime Meridian (0°).',
 explanation:'Together, latitude and longitude form a grid that gives every place on Earth an exact "address". The Equator divides Earth into Northern and Southern hemispheres; the Prime Meridian divides it into Eastern and Western hemispheres.',
 teacherTip:'LATitude lines lie "flat" like the rungs of a ladder.',
 examTip:'Total latitudes = 181 (including Equator); total longitudes = 360.'},
{id:"geo-c1tf1",topicId:"geo-ch1",type:"true_false",subtopic:"Objective Questions",
 question:"A globe can show a small area such as a town in great detail.",
 correctAnswer:"false",answer:"False. A globe shows the whole Earth and cannot zoom into small areas; a large-scale map is used for that.",
 teacherTip:'You cannot find your street on a globe.',examTip:'Match the tool to the task: globe for the whole Earth, map for parts.'},
{id:"geo-c1tf2",topicId:"geo-ch1",type:"true_false",subtopic:"Objective Questions",
 question:"The Representative Fraction (R.F.) of a map has no units.",
 correctAnswer:"true",answer:"True. R.F. compares two distances measured in the same unit, so the units cancel out.",
 teacherTip:'Same units top and bottom = units vanish.',examTip:'Always state R.F. as a ratio like 1:50000.'},
{id:"geo-c1fb1",topicId:"geo-ch1",type:"fill_blank",subtopic:"Objective Questions",
 question:"The 0° line of latitude is called the ______.",
 blankAnswer:"equator",answer:"The 0° line of latitude is called the Equator.",
 teacherTip:'It is the longest latitude.',examTip:'The Equator divides the Earth into Northern and Southern hemispheres.'},
{id:"geo-c1mcq1",topicId:"geo-ch1",type:"mcq",subtopic:"Objective Questions",
 question:"Which scale remains correct even if the map is photo-enlarged or reduced?",
 options:["Statement scale","Representative Fraction","Linear (graphical) scale","Verbal scale"],correctOption:2,
 answer:"A linear/graphical scale enlarges or reduces along with the map, so it always stays accurate.",
 teacherTip:'The bar shrinks and grows with the paper.',examTip:'This is the key merit of a linear scale.'},
{id:"geo-c1sa1",topicId:"geo-ch1",type:"short_answer",subtopic:"Short/Long Answer",
 question:"State three advantages of a map over a globe.",
 answer:'1. A map can show a small area (city/street) in great detail. 2. Maps are flat, light and easy to fold and carry. 3. Many maps (relief, political, thematic) can be drawn for different purposes; a globe shows only one general view.',
 teacherTip:'Detail, Portability, Variety.',examTip:'Give exactly three crisp points for a 3-mark question.'},

// ===================== CH 2: INTERIOR OF THE EARTH =====================
{id:"geo-c2n1",topicId:"geo-ch2",type:"note",subtopic:"Three Layers of the Earth",
 content:'The Earth is made of three concentric layers: the CRUST (outermost, thin), the MANTLE (middle, thickest), and the CORE (innermost, made mainly of iron and nickel).',
 explanation:'Think of the Earth like an apple: the thin skin is the crust, the thick flesh is the mantle, and the seeds in the centre are the core. The core is divided into a liquid outer core and a solid inner core.',
 teacherTip:'Apple model: skin → crust, flesh → mantle, seed → core.',
 examTip:'Name the layers from outside to inside in order for full marks.'},
{id:"geo-c2n2",topicId:"geo-ch2",type:"note",subtopic:"SIAL, SIMA and NIFE",
 content:'The continental crust is rich in Silica and Aluminium (SIAL); the oceanic crust is rich in Silica and Magnesium (SIMA); the core is made of Nickel (Ni) and Iron (Fe), hence NIFE.',
 explanation:'These names are simply made from the main elements found in each zone, which helps geographers describe what each layer is built from.',
 teacherTip:'SIAL = continents, SIMA = ocean floors, NIFE = core.',
 examTip:'Write the full forms of SIAL, SIMA and NIFE.'},
{id:"geo-c2tf1",topicId:"geo-ch2",type:"true_false",subtopic:"Objective Questions",
 question:"The mantle is the thickest layer of the Earth.",
 correctAnswer:"true",answer:"True. The mantle lies between the crust and the core and is the thickest of the three layers.",
 teacherTip:'The "flesh of the apple" is the thickest part.',examTip:'Do not confuse thickest (mantle) with densest (core).'},
{id:"geo-c2fb1",topicId:"geo-ch2",type:"fill_blank",subtopic:"Objective Questions",
 question:"The innermost layer of the Earth is called the ______.",
 blankAnswer:"core",answer:"The innermost layer of the Earth is called the core.",
 teacherTip:'It is made mainly of iron and nickel.',examTip:'The outer core is liquid; the inner core is solid.'},
{id:"geo-c2mcq1",topicId:"geo-ch2",type:"mcq",subtopic:"Objective Questions",
 question:"Which layer is described by the term NIFE?",
 options:["Crust","Mantle","Core","Atmosphere"],correctOption:2,
 answer:"NIFE (Nickel + Ferrum/Iron) describes the composition of the Earth's core.",
 teacherTip:'Fe is the symbol for iron.',examTip:'Link each acronym to its layer.'},

// ===================== CH 3: EARTHQUAKES & VOLCANOES =====================
{id:"geo-c3n1",topicId:"geo-ch3",type:"note",subtopic:"What is an Earthquake?",
 content:'An EARTHQUAKE is the sudden shaking or trembling of the Earth\u2019s surface caused by the release of energy along faults inside the crust. The point of origin underground is the FOCUS; the point directly above it on the surface is the EPICENTRE.',
 explanation:'When rocks under stress suddenly slip, the stored energy travels outward as seismic waves, shaking the ground. The damage is usually greatest at the epicentre.',
 teacherTip:'Focus is "deep below"; Epicentre is "exactly above" on the surface.',
 examTip:'Earthquake strength is measured on the Richter scale using a seismograph.'},
{id:"geo-c3n2",topicId:"geo-ch3",type:"note",subtopic:"Parts of a Volcano",
 content:'A VOLCANO is an opening in the Earth\u2019s crust through which molten rock (magma), gases and ash escape. Magma below the surface is called LAVA once it reaches the surface.',
 explanation:'Magma collects in a magma chamber, rises through a pipe-like vent, and erupts from the crater at the top. Volcanoes can be active, dormant or extinct.',
 teacherTip:'Magma is "inside"; Lava is "out in the air".',
 examTip:'Classify volcanoes as active, dormant or extinct with one example each.'},
{id:"geo-c3tf1",topicId:"geo-ch3",type:"true_false",subtopic:"Objective Questions",
 question:"The epicentre of an earthquake lies below the focus.",
 correctAnswer:"false",answer:"False. The epicentre lies on the surface directly ABOVE the focus.",
 teacherTip:'Focus down, epicentre up.',examTip:'Draw a labelled diagram to avoid this mix-up.'},
{id:"geo-c3fb1",topicId:"geo-ch3",type:"fill_blank",subtopic:"Objective Questions",
 question:"The instrument used to record earthquake waves is the ______.",
 blankAnswer:"seismograph",answer:"The instrument used to record earthquake waves is the seismograph.",
 teacherTip:'Its records are called seismograms.',examTip:'Magnitude is given on the Richter scale.'},
{id:"geo-c3mcq1",topicId:"geo-ch3",type:"mcq",subtopic:"Objective Questions",
 question:"Molten rock that has reached the Earth\u2019s surface is called:",
 options:["Magma","Lava","Crater","Vent"],correctOption:1,
 answer:"Once magma reaches the surface during an eruption, it is called lava.",
 teacherTip:'Surface = Lava.',examTip:'Distinguish magma and lava in one line.'},

// ===================== CH 4: WEATHERING & SOIL =====================
{id:"geo-c4n1",topicId:"geo-ch4",type:"note",subtopic:"Weathering",
 content:'WEATHERING is the breaking down of rocks into smaller pieces at or near the Earth\u2019s surface, without movement. It can be Physical (mechanical), Chemical, or Biological.',
 explanation:'Heat, water, frost, chemicals and living things slowly crack and crumble rocks where they lie. Weathering is the first step in the formation of soil.',
 teacherTip:'Weathering = "breaking in place"; Erosion = "breaking + carrying away".',
 examTip:'Name the three types of weathering with one cause each.'},
{id:"geo-c4n2",topicId:"geo-ch4",type:"note",subtopic:"Soil and Its Profile",
 content:'SOIL is the thin upper layer of loose material on the Earth\u2019s surface made of weathered rock, humus, water and air. A vertical section showing its layers (horizons) is the SOIL PROFILE.',
 explanation:'The top layer (topsoil) is dark and rich in humus, supporting plants. Below it lies subsoil, then weathered parent rock, and finally solid bedrock.',
 teacherTip:'Topsoil is the "living" layer where plants grow.',
 examTip:'Humus is decayed organic matter that makes soil fertile.'},
{id:"geo-c4tf1",topicId:"geo-ch4",type:"true_false",subtopic:"Objective Questions",
 question:"Weathering always involves the movement of broken rock material.",
 correctAnswer:"false",answer:"False. Weathering breaks rock in place; movement of material is erosion.",
 teacherTip:'No transport = weathering.',examTip:'Keep weathering and erosion separate.'},
{id:"geo-c4fb1",topicId:"geo-ch4",type:"fill_blank",subtopic:"Objective Questions",
 question:"Decayed organic matter that makes soil fertile is called ______.",
 blankAnswer:"humus",answer:"Decayed organic matter that makes soil fertile is called humus.",
 teacherTip:'It gives topsoil its dark colour.',examTip:'Humus improves soil fertility and water retention.'},

// ===================== CH 5: POLLUTION =====================
{id:"geo-c5n1",topicId:"geo-ch5",type:"note",subtopic:"What is Pollution?",
 content:'POLLUTION is the contamination of air, water or land by harmful substances called POLLUTANTS, which damage the environment and the health of living things.',
 explanation:'Smoke from vehicles and factories, sewage in rivers, and garbage on land are all pollutants. Pollution is mainly caused by human activities.',
 teacherTip:'Pollutant = the harmful substance; Pollution = the act of contaminating.',
 examTip:'Classify pollution as air, water, land (soil) and noise pollution.'},
{id:"geo-c5n2",topicId:"geo-ch5",type:"note",subtopic:"The Greenhouse Effect",
 content:'The GREENHOUSE EFFECT is the trapping of heat near the Earth\u2019s surface by gases such as carbon dioxide and methane. Excess greenhouse gases cause GLOBAL WARMING.',
 explanation:'Some warming is natural and keeps the planet livable, but burning fossil fuels adds extra gases that trap too much heat, slowly raising global temperatures.',
 teacherTip:'Greenhouse gases act like a blanket around the Earth.',
 examTip:'Name two greenhouse gases: carbon dioxide and methane.'},
{id:"geo-c5tf1",topicId:"geo-ch5",type:"true_false",subtopic:"Objective Questions",
 question:"Carbon dioxide is a greenhouse gas.",
 correctAnswer:"true",answer:"True. Carbon dioxide traps heat in the atmosphere and is a major greenhouse gas.",
 teacherTip:'CO\u2082 is released by burning fuels.',examTip:'Link greenhouse gases to global warming.'},
{id:"geo-c5fb1",topicId:"geo-ch5",type:"fill_blank",subtopic:"Objective Questions",
 question:"Unwanted, harmful sound is known as ______ pollution.",
 blankAnswer:"noise",answer:"Unwanted, harmful sound is known as noise pollution.",
 teacherTip:'Loud horns and machines are major sources.',examTip:'Noise is measured in decibels (dB).'},

// ===================== CH 6: NATURAL RESOURCES =====================
{id:"geo-c6n1",topicId:"geo-ch6",type:"note",subtopic:"Renewable vs Non-Renewable",
 content:'RENEWABLE resources (sunlight, wind, water, forests) can be replaced by nature within a short time. NON-RENEWABLE resources (coal, petroleum, natural gas) take millions of years to form and can get exhausted.',
 explanation:'We must use non-renewable resources carefully because once they run out, they cannot be made again in our lifetime. Renewable resources can still be damaged if overused.',
 teacherTip:'Renewable = "Refills quickly"; Non-renewable = "Never refills in time".',
 examTip:'Give two examples of each type.'},
{id:"geo-c6n2",topicId:"geo-ch6",type:"note",subtopic:"Conservation of Resources",
 content:'CONSERVATION is the careful and wise use of natural resources so that they last longer and are available for future generations. The 3 R\u2019s are Reduce, Reuse, Recycle.',
 explanation:'Saving water and electricity, recycling paper and metals, and protecting forests are all ways to conserve resources for the people who come after us.',
 teacherTip:'Remember the 3 R\u2019s: Reduce, Reuse, Recycle.',
 examTip:'Define conservation and list the 3 R\u2019s.'},
{id:"geo-c6tf1",topicId:"geo-ch6",type:"true_false",subtopic:"Objective Questions",
 question:"Coal and petroleum are renewable resources.",
 correctAnswer:"false",answer:"False. Coal and petroleum are non-renewable; they take millions of years to form.",
 teacherTip:'Fossil fuels are non-renewable.',examTip:'Solar and wind are renewable alternatives.'},
{id:"geo-c6mcq1",topicId:"geo-ch6",type:"mcq",subtopic:"Objective Questions",
 question:"Which of these is a renewable resource?",
 options:["Coal","Natural gas","Solar energy","Petroleum"],correctOption:2,
 answer:"Solar energy is renewable because sunlight is continuously available.",
 teacherTip:'If nature refills it quickly, it is renewable.',examTip:'Sun, wind and water are classic renewables.'},

// ===================== CH 7: AGRICULTURE =====================
{id:"geo-c7n1",topicId:"geo-ch7",type:"note",subtopic:"What is Agriculture?",
 content:'AGRICULTURE is the practice of cultivating crops and rearing animals for food and raw materials. It is the primary occupation of a large part of India\u2019s population.',
 explanation:'Farming gives us food grains, vegetables, fruits and raw materials like cotton and jute for industries. It depends heavily on soil, climate and water supply.',
 teacherTip:'Agriculture is a "primary" activity (it uses nature directly).',
 examTip:'Mention that agriculture provides both food and raw materials.'},
{id:"geo-c7n2",topicId:"geo-ch7",type:"note",subtopic:"Kharif and Rabi Crops",
 content:'KHARIF crops are sown in the rainy season (June\u2013July) and harvested in autumn, e.g. rice, maize, cotton. RABI crops are sown in winter (October\u2013November) and harvested in spring, e.g. wheat, gram, mustard.',
 explanation:'India\u2019s two main cropping seasons follow the monsoon. Kharif crops need plenty of water and warmth; Rabi crops grow in the cooler, drier winter months.',
 teacherTip:'Kharif = monsoon crops; Rabi = winter crops.',
 examTip:'Give two examples each of Kharif and Rabi crops.'},
{id:"geo-c7tf1",topicId:"geo-ch7",type:"true_false",subtopic:"Objective Questions",
 question:"Wheat is a Kharif crop.",
 correctAnswer:"false",answer:"False. Wheat is a Rabi crop, sown in winter and harvested in spring.",
 teacherTip:'Wheat = Rabi (winter).',examTip:'Rice is the main Kharif example.'},
{id:"geo-c7fb1",topicId:"geo-ch7",type:"fill_blank",subtopic:"Objective Questions",
 question:"Crops sown with the onset of the monsoon are called ______ crops.",
 blankAnswer:"kharif",answer:"Crops sown with the onset of the monsoon are called Kharif crops.",
 teacherTip:'Rain arrives, Kharif begins.',examTip:'Rice, maize and cotton are Kharif crops.'},

// ===================== CH 8: INDUSTRIES =====================
{id:"geo-c8n1",topicId:"geo-ch8",type:"note",subtopic:"What is an Industry?",
 content:'An INDUSTRY is an economic activity that processes raw materials into more useful finished goods. Industries may be classified by size (large/small), raw material (agro/mineral based) or ownership (public/private).',
 explanation:'A cotton mill turning raw cotton into cloth, or a steel plant turning iron ore into steel, are industries. They add value to raw materials and create jobs.',
 teacherTip:'Industry = turning raw materials into useful products.',
 examTip:'Classify industries on at least two different bases.'},
{id:"geo-c8n2",topicId:"geo-ch8",type:"note",subtopic:"Agro-based vs Mineral-based",
 content:'AGRO-BASED industries use raw materials from agriculture (e.g. cotton textile, sugar). MINERAL-BASED industries use minerals as raw material (e.g. iron and steel, cement).',
 explanation:'The two groups differ in where their raw materials come from \u2014 the farm or the mine \u2014 which often decides where the industry is located.',
 teacherTip:'Agro = from farms; Mineral = from mines.',
 examTip:'Give one example of each type.'},
{id:"geo-c8tf1",topicId:"geo-ch8",type:"true_false",subtopic:"Objective Questions",
 question:"The iron and steel industry is a mineral-based industry.",
 correctAnswer:"true",answer:"True. It uses iron ore (a mineral) as its main raw material.",
 teacherTip:'Ore from a mine = mineral-based.',examTip:'Cotton textiles, by contrast, are agro-based.'},
{id:"geo-c8mcq1",topicId:"geo-ch8",type:"mcq",subtopic:"Objective Questions",
 question:"Which of the following is an agro-based industry?",
 options:["Cement","Iron and steel","Sugar","Aluminium"],correctOption:2,
 answer:"The sugar industry uses sugarcane (an agricultural product), so it is agro-based.",
 teacherTip:'Trace the raw material back to a farm.',examTip:'Sugar and cotton textiles are common agro-based examples.'},
];
