// ============================================================
// ICSE CLASS 8 HISTORY & CIVICS — 14 CHAPTERS
// Original content written for StudyHub
// History: 10 chapters | Civics: 4 chapters
// ============================================================
const HISTORY_CIVICS_DATA = [

// ====================== HISTORY SECTION ======================

// ====== H-CH1: A PERIOD OF TRANSITION ======
{id:"hc1n1",topicId:"hist-ch1",type:"note",subtopic:"The Renaissance",content:'The RENAISSANCE (14th-17th century) was a cultural and intellectual rebirth that began in Italy and spread across Europe. It marked the transition from the Medieval to the Modern Age. Key features: revival of Greek and Roman learning, emphasis on humanism (human reason and individual worth), advances in art (Leonardo da Vinci, Michelangelo), science, and literature.',explanation:'Before the Renaissance, the Church dominated all thought. The Renaissance said: "Humans can think for themselves!" This sparked a revolution in art, science, and philosophy.',teacherTip:'Renaissance = "Rebirth" in French. It was a rebirth of classical knowledge and thinking.',examTip:'Name at least 3 features of the Renaissance and 2 famous personalities.'},
{id:"hc1n2",topicId:"hist-ch1",type:"note",subtopic:"The Reformation",content:'The REFORMATION (16th century) was a religious movement against the corruption in the Catholic Church, led by MARTIN LUTHER (1517 — nailed 95 Theses to a church door in Germany). He opposed the sale of indulgences (paying money for forgiveness of sins). This led to the birth of PROTESTANTISM — a new branch of Christianity separate from the Catholic Church.',explanation:'Luther believed that salvation comes through faith alone, not by paying money to the Church. His protest split Christianity into Catholics and Protestants.',teacherTip:'Luther\'s 95 Theses = 95 complaints against the Church. Like a formal protest letter!',examTip:'Know: Who started it (Luther), When (1517), Why (sale of indulgences), Result (Protestantism).'},
{id:"hc1n3",topicId:"hist-ch1",type:"note",subtopic:"Geographical Discoveries",content:'The AGE OF EXPLORATION (15th-17th century): Europeans explored new sea routes and lands. Key voyages: VASCO DA GAMA — reached India via sea route around Africa (1498). CHRISTOPHER COLUMBUS — discovered America (1492, thought it was India). FERDINAND MAGELLAN — first to circumnavigate the globe. Causes: desire for spices and trade, spread of Christianity, advances in navigation (compass, astrolabe).',explanation:'Europeans wanted spices from India but the land route was dangerous and controlled by Arabs. So they searched for sea routes, accidentally discovering entire continents along the way!',teacherTip:'Columbus found America by mistake — he thought he had reached India! That\'s why Native Americans were called "Indians."',examTip:'Match each explorer with their achievement and year for full marks.'},
// T/F
{id:"hc1tf1",topicId:"hist-ch1",type:"true_false",subtopic:"Objective Questions",question:"The Renaissance began in France.",correctAnswer:"false",answer:"False. The Renaissance began in ITALY (specifically in cities like Florence, Venice, and Rome) and then spread to the rest of Europe.",teacherTip:'Italy was the centre because it had wealthy merchant families (like the Medici) who sponsored art and learning.',examTip:'Always state Italy as the origin of the Renaissance.'},
{id:"hc1tf2",topicId:"hist-ch1",type:"true_false",subtopic:"Objective Questions",question:"Martin Luther opposed the sale of indulgences.",correctAnswer:"true",answer:"True. Luther believed that forgiveness could not be bought with money. He nailed his 95 Theses to a church door in Wittenberg, Germany in 1517 to protest this practice.",teacherTip:'Indulgences = paying money to the Church for forgiveness. Luther said this was wrong.',examTip:'Mention "95 Theses" and "1517" when discussing Luther.'},
// MCQ
{id:"hc1mcq1",topicId:"hist-ch1",type:"mcq",subtopic:"Objective Questions",question:"Who discovered the sea route to India?",options:["Christopher Columbus","Ferdinand Magellan","Vasco da Gama","Marco Polo"],correctOption:2,answer:"Vasco da Gama, a Portuguese explorer, reached Calicut (Kerala) in India in 1498 by sailing around the Cape of Good Hope in Africa.",teacherTip:'Vasco da Gama = India. Columbus = America. Magellan = circumnavigation.',examTip:'Remember the year 1498 and the port city Calicut.'},
// Short answer
{id:"hc1sa1",topicId:"hist-ch1",type:"short_answer",subtopic:"Short/Long Answer",question:"What was the Renaissance? Mention three important features.",answer:'The RENAISSANCE was a cultural and intellectual movement that began in Italy in the 14th century, marking the transition from medieval to modern times. The word means "Rebirth."\n\nThree important features:\n1. Revival of interest in ancient Greek and Roman art, literature, and philosophy\n2. Rise of HUMANISM — emphasis on human reason, individual worth, and secular (non-religious) thinking\n3. Great advances in art (realistic painting, perspective), science (Copernicus, Galileo), and literature (Shakespeare, Dante)',teacherTip:'The Renaissance changed HOW people thought — from blind faith to reason and inquiry.',examTip:'Define the term, give the origin (Italy), and list at least 3 features with examples.'},

// ====== H-CH2: GROWTH OF NATIONALISM ======
{id:"hc2n1",topicId:"hist-ch2",type:"note",subtopic:"French Revolution (1789)",content:'The FRENCH REVOLUTION (1789) overthrew the monarchy of King Louis XVI and established a republic based on the principles of LIBERTY, EQUALITY, and FRATERNITY. Causes: heavy taxation of the poor, extravagant spending by the king, food shortages, influence of Enlightenment thinkers (Rousseau, Voltaire). Key event: Storming of the Bastille prison (July 14, 1789). Outcome: Declaration of Rights of Man, end of feudalism, eventual rise of Napoleon.',explanation:'The common people of France were starving while the king and nobles lived in luxury. Inspired by ideas of freedom and equality, they rose up and changed the course of history.',teacherTip:'July 14 (Bastille Day) is France\'s Independence Day — like India\'s August 15.',examTip:'Know: Causes (at least 3), Key date (1789), Slogan (Liberty, Equality, Fraternity), Outcome.'},
{id:"hc2n2",topicId:"hist-ch2",type:"note",subtopic:"Unification of Italy and Germany",content:'UNIFICATION OF ITALY: Led by Count Cavour (Prime Minister of Sardinia), Giuseppe Mazzini (idealist), and Giuseppe Garibaldi (military leader). Italy was unified by 1871 with Victor Emmanuel II as the first king.\nUNIFICATION OF GERMANY: Led by Otto von Bismarck (Chancellor of Prussia) through his "Blood and Iron" policy — using wars to unite German states. Germany was unified in 1871 with Kaiser Wilhelm I as emperor.',explanation:'Both Italy and Germany were made up of many small independent states. Nationalist leaders united them into single powerful nations through a mix of diplomacy and warfare.',teacherTip:'Italy = Cavour + Mazzini + Garibaldi. Germany = Bismarck + "Blood and Iron."',examTip:'Compare the unification of Italy and Germany — methods, leaders, and year (both 1871).'},
// T/F
{id:"hc2tf1",topicId:"hist-ch2",type:"true_false",subtopic:"Objective Questions",question:"The French Revolution began in 1776.",correctAnswer:"false",answer:"False. The French Revolution began in 1789. The year 1776 is when the American Declaration of Independence was signed.",teacherTip:'1776 = America. 1789 = France. Don\'t mix them up!',examTip:'Both are revolutions but different countries and years.'},
// MCQ
{id:"hc2mcq1",topicId:"hist-ch2",type:"mcq",subtopic:"Objective Questions",question:"Who led the unification of Germany?",options:["Garibaldi","Mazzini","Bismarck","Cavour"],correctOption:2,answer:'Otto von Bismarck, the Chancellor of Prussia, unified Germany through his "Blood and Iron" policy using three wars (Danish, Austro-Prussian, Franco-Prussian).',teacherTip:'Bismarck = Germany. Garibaldi/Cavour/Mazzini = Italy.',examTip:'Mention "Blood and Iron" policy when discussing Bismarck.'},
// Short answer
{id:"hc2sa1",topicId:"hist-ch2",type:"short_answer",subtopic:"Short/Long Answer",question:"What were the main causes of the French Revolution?",answer:'Main causes of the French Revolution (1789):\n\n1. SOCIAL INEQUALITY: French society was divided into three Estates — Clergy (First), Nobles (Second), and Common People (Third). The Third Estate paid most taxes but had no political power.\n\n2. FINANCIAL CRISIS: Extravagant spending by King Louis XVI and Queen Marie Antoinette, wars, and heavy debts emptied the treasury.\n\n3. FOOD SHORTAGES: Bad harvests led to bread shortages and rising prices, causing widespread hunger.\n\n4. ENLIGHTENMENT IDEAS: Thinkers like Rousseau ("Social Contract"), Voltaire (freedom of speech), and Montesquieu (separation of powers) inspired people to demand their rights.\n\n5. WEAK LEADERSHIP: Louis XVI was an indecisive king unable to handle the crisis.',teacherTip:'Think: Inequality + Bankruptcy + Hunger + New Ideas + Weak King = Revolution!',examTip:'List at least 4 causes with brief explanation for each.'},

// ====== H-CH3: AMERICAN CIVIL WAR ======
{id:"hc3n1",topicId:"hist-ch3",type:"note",subtopic:"American Civil War (1861-1865)",content:'The AMERICAN CIVIL WAR (1861-1865) was fought between the NORTHERN states (Union, anti-slavery) and SOUTHERN states (Confederacy, pro-slavery). Main cause: SLAVERY — the South depended on slave labour for cotton plantations, while the North wanted to abolish slavery. President ABRAHAM LINCOLN led the Union. Key outcome: Union victory, abolition of slavery (13th Amendment), preservation of the United States as one nation.',explanation:'The North was industrial and didn\'t need slaves. The South was agricultural and depended on slaves for cotton farming. This fundamental disagreement tore the nation apart.',teacherTip:'North = Free states = Industry. South = Slave states = Agriculture (cotton). Lincoln = the "Great Emancipator."',examTip:'Know: Dates (1861-65), Sides (North vs South), Leader (Lincoln), Cause (slavery), Result (abolition).'},
// T/F
{id:"hc3tf1",topicId:"hist-ch3",type:"true_false",subtopic:"Objective Questions",question:"Abraham Lincoln was the President of the Confederate states.",correctAnswer:"false",answer:"False. Abraham Lincoln was the President of the UNION (Northern states). Jefferson Davis was the President of the Confederate (Southern) states.",teacherTip:'Lincoln = Union = North = Anti-slavery. Davis = Confederacy = South = Pro-slavery.',examTip:'Never confuse Lincoln with the Confederacy — he fought AGAINST slavery.'},
// Short answer
{id:"hc3sa1",topicId:"hist-ch3",type:"short_answer",subtopic:"Short/Long Answer",question:"What were the causes and results of the American Civil War?",answer:'CAUSES:\n1. Slavery — South wanted to keep it; North wanted to abolish it\n2. Economic differences — North (industrial) vs South (agricultural/plantation)\n3. States\' rights — South believed each state should decide its own laws\n4. Election of Abraham Lincoln (1860) — South feared he would end slavery\n\nRESULTS:\n1. Union (North) won the war in 1865\n2. Slavery abolished through the 13th Amendment to the Constitution\n3. United States preserved as one nation\n4. Lincoln assassinated in 1865 shortly after the war ended\n5. Reconstruction period to rebuild the South',teacherTip:'The Civil War answered two big questions: Is slavery acceptable? (No) Can states leave the Union? (No)',examTip:'List at least 3 causes and 3 results separately.'},

// ====== H-CH4 & H-CH5: TRADERS TO RULERS (British in India) ======
{id:"hc4n1",topicId:"hist-ch4",type:"note",subtopic:"East India Company Arrives",content:'The BRITISH EAST INDIA COMPANY came to India in 1600 for TRADE (spices, cotton, silk). First factory at SURAT (1613). Key events: Battle of PLASSEY (1757) — Robert Clive defeated Siraj-ud-Daulah (Nawab of Bengal) with the help of traitor Mir Jafar. This gave British control over Bengal. Battle of BUXAR (1764) — confirmed British supremacy. British used policies like Subsidiary Alliance and Doctrine of Lapse to annex Indian states.',explanation:'The British came as traders but slowly became rulers. They exploited divisions among Indian rulers, used bribes and military power, and took over one state after another.',teacherTip:'Came for trade → Won wars → Made alliances → Became rulers. A 150-year takeover!',examTip:'Know Battle of Plassey (1757) and Buxar (1764) — dates, who fought, and results.'},
{id:"hc4n2",topicId:"hist-ch4",type:"note",subtopic:"Policies of Expansion",content:'British used several policies to expand control: (1) SUBSIDIARY ALLIANCE (Lord Wellesley) — Indian rulers had to keep British troops and pay for them, couldn\'t keep their own army or make alliances. (2) DOCTRINE OF LAPSE (Lord Dalhousie) — if a ruler died without a natural heir, his state would be annexed by the British. States annexed: Satara, Jhansi, Nagpur, Awadh.',explanation:'These clever policies let the British take over India without always fighting wars. Rulers who signed the Subsidiary Alliance lost their independence, and the Doctrine of Lapse just grabbed states when rulers died.',teacherTip:'Subsidiary Alliance = "Pay for our army + lose your own." Doctrine of Lapse = "No natural son? We take your kingdom."',examTip:'Name the Governor-General who introduced each policy AND list states annexed.'},
// T/F
{id:"hc4tf1",topicId:"hist-ch4",type:"true_false",subtopic:"Objective Questions",question:"The Battle of Plassey was fought in 1764.",correctAnswer:"false",answer:"False. The Battle of Plassey was fought in 1757. The Battle of Buxar was fought in 1764.",teacherTip:'Plassey = 1757, Buxar = 1764. Both were turning points for British power in India.',examTip:'Remember: P comes before B alphabetically, 57 comes before 64 chronologically.'},
// MCQ
{id:"hc4mcq1",topicId:"hist-ch4",type:"mcq",subtopic:"Objective Questions",question:"The Doctrine of Lapse was introduced by:",options:["Lord Wellesley","Lord Dalhousie","Robert Clive","Warren Hastings"],correctOption:1,answer:"Lord Dalhousie introduced the Doctrine of Lapse, which stated that if an Indian ruler died without a natural male heir, his kingdom would be annexed by the British.",teacherTip:'Dalhousie = Doctrine of Lapse. Wellesley = Subsidiary Alliance.',examTip:'Name at least 2 states annexed under this doctrine (Satara, Jhansi, Nagpur).'},
// Short answer
{id:"hc4sa1",topicId:"hist-ch4",type:"short_answer",subtopic:"Short/Long Answer",question:"Explain the Subsidiary Alliance and the Doctrine of Lapse.",answer:'SUBSIDIARY ALLIANCE (Lord Wellesley):\n• Indian rulers had to accept a British Resident in their court\n• They had to maintain British troops and pay for them\n• They could not keep their own army or make treaties with other states\n• In return, British promised to protect them from enemies\n• This made rulers completely dependent on the British\n\nDOCTRINE OF LAPSE (Lord Dalhousie):\n• If a ruler died without a natural male heir, his state would be annexed by the British\n• Adopted sons were not recognized as legal heirs\n• States annexed: Satara (1848), Jhansi (1854), Nagpur (1854), Awadh (1856)\n• This policy caused great resentment and was a major cause of the 1857 Revolt',teacherTip:'Both policies were designed to expand British territory without direct war.',examTip:'Explain BOTH policies with examples of states affected.'},

// ====== H-CH6: IMPACT OF BRITISH RULE ======
{id:"hc6n1",topicId:"hist-ch6",type:"note",subtopic:"Economic Impact of British Rule",content:'The British exploited India economically: (1) DRAIN OF WEALTH — India\'s raw materials were taken to Britain, manufactured goods sent back at high prices. (2) DESTRUCTION OF INDIAN INDUSTRIES — traditional handicrafts (muslin, silk) destroyed as machine-made British goods flooded markets. (3) LAND REVENUE SYSTEMS — Permanent Settlement (Bengal), Ryotwari, Mahalwari — all extracted maximum revenue from farmers. (4) FAMINES — British policies caused severe famines (Bengal Famine killed millions).',explanation:'India was once called the "Golden Bird" because of its wealth. British rule drained this wealth to England, destroyed local industries, and impoverished millions of Indian farmers and artisans.',teacherTip:'India went from exporter to importer under British rule. Our cloth was world-famous, then Britain destroyed it.',examTip:'Explain "Drain of Wealth" theory (Dadabhai Naoroji coined this term).'},
// Short answer
{id:"hc6sa1",topicId:"hist-ch6",type:"short_answer",subtopic:"Short/Long Answer",question:"What was the economic impact of British rule on India?",answer:'NEGATIVE ECONOMIC IMPACTS:\n\n1. DRAIN OF WEALTH: Raw materials (cotton, jute, indigo) taken to Britain cheaply; finished goods sold back to India at high prices. Dadabhai Naoroji called this the "Drain of Wealth."\n\n2. DESTRUCTION OF HANDICRAFTS: Traditional Indian industries (muslin weavers, silk workers) destroyed because they could not compete with cheap British machine-made goods. Artisans lost their livelihoods.\n\n3. EXPLOITATION OF FARMERS: Heavy land taxes through Permanent Settlement, Ryotwari, and Mahalwari systems left farmers in perpetual debt and poverty.\n\n4. COMMERCIALIZATION OF AGRICULTURE: Farmers forced to grow cash crops (indigo, opium) instead of food crops, leading to food shortages and famines.\n\n5. FAMINES: British policies led to devastating famines — the Bengal Famine of 1770 killed 10 million people.',teacherTip:'India was rich BEFORE British rule and poor AFTER. That tells the whole story.',examTip:'Mention Dadabhai Naoroji and his "Drain of Wealth" theory for extra marks.'},

// ====== H-CH7: THE GREAT UPRISING OF 1857 ======
{id:"hc7n1",topicId:"hist-ch7",type:"note",subtopic:"Revolt of 1857",content:'The REVOLT OF 1857 (also called the First War of Independence) was the first major uprising against British rule. IMMEDIATE CAUSE: Greased cartridges of Enfield rifles rumoured to contain cow and pig fat (offensive to both Hindus and Muslims). LEADERS: Mangal Pandey (Barrackpore), Rani Lakshmibai (Jhansi), Nana Sahib (Kanpur), Tantia Tope, Bahadur Shah Zafar (Delhi, declared symbolic emperor). CAUSES: Doctrine of Lapse, economic exploitation, racial discrimination, disrespect for Indian culture. RESULT: Revolt suppressed. East India Company abolished. British Crown took direct control of India (1858).',explanation:'Years of anger over British exploitation, cultural insensitivity, and loss of kingdoms erupted in 1857. Though the revolt failed due to lack of unity and planning, it shook the British Empire.',teacherTip:'The cartridge issue was just the spark — the real fuel was decades of British oppression.',examTip:'List at least 4 causes, 4 leaders with their centres, and 3 results of the revolt.'},
// T/F
{id:"hc7tf1",topicId:"hist-ch7",type:"true_false",subtopic:"Objective Questions",question:"The Revolt of 1857 succeeded in overthrowing British rule.",correctAnswer:"false",answer:"False. The Revolt of 1857 was ultimately suppressed by the British. However, it led to the end of the East India Company, and the British Crown took direct control of India through the Government of India Act, 1858.",teacherTip:'The revolt failed militarily but succeeded in ending Company rule.',examTip:'Always mention BOTH the failure AND its important consequence (Crown takes over).'},
// MCQ
{id:"hc7mcq1",topicId:"hist-ch7",type:"mcq",subtopic:"Objective Questions",question:"Who was the first soldier to rebel in 1857?",options:["Tantia Tope","Mangal Pandey","Nana Sahib","Bahadur Shah Zafar"],correctOption:1,answer:"Mangal Pandey, a sepoy at Barrackpore, refused to use the greased cartridges and attacked his British officer on March 29, 1857. He was executed on April 8, 1857.",teacherTip:'Mangal Pandey fired the first shot of the revolt at Barrackpore.',examTip:'Know the date (March 29, 1857) and place (Barrackpore) of the first incident.'},

// ====== H-CH8: REFORMERS AND REFORM MOVEMENTS ======
{id:"hc8n1",topicId:"hist-ch8",type:"note",subtopic:"Social Reformers of India",content:'19th century India saw great social reform movements:\n(1) RAJA RAM MOHAN ROY — "Father of Indian Renaissance." Founded Brahmo Samaj (1828). Fought against Sati, child marriage, caste system. Promoted modern education and women\'s rights. Helped ban Sati (1829).\n(2) ISHWAR CHANDRA VIDYASAGAR — championed widow remarriage (Widow Remarriage Act, 1856), women\'s education.\n(3) SWAMI DAYANAND SARASWATI — founded Arya Samaj (1875). Motto: "Back to the Vedas." Opposed idol worship, caste discrimination.\n(4) JYOTIRAO PHULE — fought for lower caste rights and women\'s education in Maharashtra.',explanation:'These reformers used reason and education to fight against evil social practices. They proved that Indian traditions could be reformed from within while keeping their core values.',teacherTip:'Ram Mohan Roy = anti-Sati. Vidyasagar = widow remarriage. Dayanand = Arya Samaj. Phule = lower caste rights.',examTip:'Know each reformer\'s contribution, organization founded, and year.'},
// Fill blank
{id:"hc8fb1",topicId:"hist-ch8",type:"fill_blank",subtopic:"Objective Questions",question:"Raja Ram Mohan Roy is called the ______ of Indian Renaissance.",blankAnswer:"Father",answer:'Raja Ram Mohan Roy is called the "Father of Indian Renaissance" because he pioneered modern thinking, social reform, and education in India.',teacherTip:'He bridged the gap between traditional India and modern Western ideas.',examTip:'Also know that he founded the Brahmo Samaj in 1828.'},
// Short answer
{id:"hc8sa1",topicId:"hist-ch8",type:"short_answer",subtopic:"Short/Long Answer",question:"Describe the contributions of Raja Ram Mohan Roy to Indian society.",answer:'RAJA RAM MOHAN ROY (1772-1833) — "Father of Indian Renaissance"\n\n1. ABOLITION OF SATI: His tireless campaign led Governor-General Lord William Bentinck to ban Sati (burning of widows) in 1829.\n\n2. BRAHMO SAMAJ (1828): Founded this reform organization to fight superstitions, idol worship, and promote monotheism (one God).\n\n3. WOMEN\'S RIGHTS: Fought for women\'s right to property and against child marriage and polygamy.\n\n4. MODERN EDUCATION: Advocated English education and Western sciences alongside Indian learning. Set up Hindu College.\n\n5. PRESS FREEDOM: Started newspapers (Sambad Kaumudi in Bengali, Mirat-ul-Akhbar in Persian) and fought for freedom of the press.\n\n6. AGAINST CASTE SYSTEM: Opposed the rigid caste system and promoted equality.',teacherTip:'Roy wanted the BEST of both worlds — Western science + Indian values.',examTip:'List at least 5 contributions with specific details (names, years).'},

// ====== H-CH9 & H-CH10: STRUGGLE FOR FREEDOM ======
{id:"hc9n1",topicId:"hist-ch9",type:"note",subtopic:"Indian National Congress & Early Nationalism",content:'The INDIAN NATIONAL CONGRESS (INC) was founded in 1885 by A.O. HUME (a retired British officer). First session in Bombay, presided by W.C. Bonnerjee. EARLY PHASE (Moderates, 1885-1905): Leaders like Dadabhai Naoroji, Gopal Krishna Gokhale, Surendranath Banerjee used petitions, prayers, and constitutional methods. They believed in British sense of justice. EXTREMIST PHASE (1905-1920): Leaders like Bal Gangadhar Tilak ("Swaraj is my birthright"), Bipin Chandra Pal, Lala Lajpat Rai (Lal-Bal-Pal) demanded Swaraj through direct action, boycotts, and Swadeshi movement.',explanation:'The freedom struggle started with polite requests (Moderates) but when the British didn\'t listen, leaders shifted to assertive demands and mass movements (Extremists).',teacherTip:'Moderates = "Please give us rights." Extremists = "We will TAKE our rights!"',examTip:'Compare Moderates and Extremists: methods, leaders, and beliefs.'},
{id:"hc10n1",topicId:"hist-ch10",type:"note",subtopic:"Gandhian Era & Independence",content:'MAHATMA GANDHI led the freedom movement from 1919 with three major movements:\n(1) NON-COOPERATION MOVEMENT (1920-22) — boycott of British goods, courts, schools. Called off after Chauri Chaura violence.\n(2) CIVIL DISOBEDIENCE MOVEMENT (1930) — Salt March (Dandi March, March 12, 1930). Gandhi walked 390 km to make salt, defying British salt tax.\n(3) QUIT INDIA MOVEMENT (1942) — "Do or Die" slogan. Demanded immediate British withdrawal.\nKey events: Jallianwala Bagh Massacre (1919), Simon Commission protest, Round Table Conferences. India gained INDEPENDENCE on AUGUST 15, 1947.',explanation:'Gandhi\'s genius was using non-violence (Ahimsa) and truth (Satyagraha) as weapons. He turned the freedom struggle into a mass movement involving millions of ordinary Indians.',teacherTip:'Gandhi\'s 3 weapons: Non-violence + Truth + Mass participation. No guns needed!',examTip:'Know all 3 movements with dates, causes, key events, and why they were called off.'},
// T/F
{id:"hc9tf1",topicId:"hist-ch9",type:"true_false",subtopic:"Objective Questions",question:"The Indian National Congress was founded by Mahatma Gandhi.",correctAnswer:"false",answer:"False. The INC was founded by A.O. HUME (Allan Octavian Hume), a retired British civil servant, in 1885. Gandhi joined the freedom movement much later, around 1919.",teacherTip:'A.O. Hume = founder of Congress. Gandhi = leader from 1919 onwards.',examTip:'Know: Founder (Hume), Year (1885), First session city (Bombay), First president (W.C. Bonnerjee).'},
{id:"hc10tf1",topicId:"hist-ch10",type:"true_false",subtopic:"Objective Questions",question:"The Dandi March was part of the Non-Cooperation Movement.",correctAnswer:"false",answer:"False. The Dandi March (Salt March, 1930) was part of the CIVIL DISOBEDIENCE MOVEMENT, not the Non-Cooperation Movement (1920-22).",teacherTip:'Non-Cooperation = 1920. Civil Disobedience/Dandi = 1930. Quit India = 1942.',examTip:'Match each movement to its correct year and key event.'},
// MCQ
{id:"hc10mcq1",topicId:"hist-ch10",type:"mcq",subtopic:"Objective Questions",question:"India gained independence on:",options:["January 26, 1947","August 15, 1947","August 15, 1950","January 26, 1950"],correctOption:1,answer:"India gained independence on August 15, 1947. January 26, 1950 is Republic Day (when the Constitution came into effect).",teacherTip:'August 15 = Independence Day. January 26 = Republic Day. Both are important but DIFFERENT!',examTip:'Know what happened on BOTH dates.'},
// Short answer
{id:"hc10sa1",topicId:"hist-ch10",type:"short_answer",subtopic:"Short/Long Answer",question:"Describe the three major movements led by Mahatma Gandhi.",answer:'1. NON-COOPERATION MOVEMENT (1920-22):\n• Boycott of British goods, courts, schools, and titles\n• Inspired by Jallianwala Bagh Massacre (1919) and Khilafat issue\n• Called off after Chauri Chaura incident (violent mob burned a police station)\n• Showed the power of mass non-violent protest\n\n2. CIVIL DISOBEDIENCE MOVEMENT (1930):\n• Started with the DANDI MARCH (Salt March) — Gandhi walked 390 km from Sabarmati Ashram to Dandi to make salt, breaking the British salt law\n• People across India defied unjust British laws\n• Led to Gandhi-Irwin Pact and Round Table Conferences\n\n3. QUIT INDIA MOVEMENT (1942):\n• Gandhi gave the call "Do or Die" demanding immediate British withdrawal\n• British arrested all major leaders\n• Underground movement continued despite suppression\n• Showed Britain that they could no longer hold India\n\nAll three movements used SATYAGRAHA (non-violent resistance) as the core strategy.',teacherTip:'1920→Non-Cooperation. 1930→Civil Disobedience. 1942→Quit India. Each escalated the pressure.',examTip:'For each movement, state: Year, Cause, Key event, Why ended/suspended, Significance.'},

// ====================== CIVICS SECTION ======================

// ====== C-CH1: THE UNION LEGISLATURE ======
{id:"cv1n1",topicId:"civ-ch1",type:"note",subtopic:"Parliament of India",content:'The UNION LEGISLATURE (Parliament) is the supreme law-making body of India. It consists of: (1) The PRESIDENT of India (head of Parliament). (2) RAJYA SABHA (Council of States) — Upper House, 250 members, represents states, members elected by state legislatures, 1/3 retire every 2 years, NOT dissolved. (3) LOK SABHA (House of the People) — Lower House, 545 members (now 543), directly elected by people, term of 5 years, can be dissolved.',explanation:'Parliament is where laws are made. Lok Sabha represents the people directly, Rajya Sabha represents the states. Both houses must agree to pass a law (except Money Bills).',teacherTip:'Lok Sabha = "People\'s House" (directly elected). Rajya Sabha = "States\' House" (indirectly elected). Lok Sabha is MORE POWERFUL.',examTip:'Compare Lok Sabha and Rajya Sabha on: members, election method, term, dissolution, and special powers.'},
{id:"cv1n2",topicId:"civ-ch1",type:"note",subtopic:"How Laws Are Made",content:'A BILL passes through these stages to become a law: (1) Introduction in either House. (2) First Reading — title and purpose. (3) Second Reading — general discussion and clause-by-clause examination by a committee. (4) Third Reading — voting (majority needed). (5) Sent to the other House — same process repeated. (6) Presidential Assent — President signs the bill into law. A MONEY BILL can only be introduced in Lok Sabha.',explanation:'Making a law is like a careful quality check. Both houses examine the bill thoroughly, and the President gives the final approval.',teacherTip:'A bill becomes an ACT (law) only after Presidential Assent.',examTip:'Know the difference between Ordinary Bill and Money Bill (where it can be introduced, Rajya Sabha\'s power).'},
// T/F
{id:"cv1tf1",topicId:"civ-ch1",type:"true_false",subtopic:"Objective Questions",question:"Rajya Sabha can be dissolved by the President.",correctAnswer:"false",answer:"False. Rajya Sabha is a PERMANENT body — it can NEVER be dissolved. Only 1/3 of its members retire every 2 years and new members are elected. Only Lok Sabha can be dissolved.",teacherTip:'Rajya Sabha = permanent/continuous. Lok Sabha = dissoluble (5-year term).',examTip:'This is a very commonly tested distinction between the two houses.'},
// MCQ
{id:"cv1mcq1",topicId:"civ-ch1",type:"mcq",subtopic:"Objective Questions",question:"A Money Bill can only be introduced in:",options:["Rajya Sabha","Lok Sabha","Either House","Joint Session"],correctOption:1,answer:"A Money Bill can ONLY be introduced in Lok Sabha (not Rajya Sabha). Rajya Sabha can only suggest amendments within 14 days but cannot reject it.",teacherTip:'Money matters = Lok Sabha\'s domain. This shows Lok Sabha\'s financial superiority.',examTip:'Rajya Sabha gets only 14 days to review a Money Bill — remember this time limit.'},

// ====== C-CH2: THE UNION EXECUTIVE ======
{id:"cv2n1",topicId:"civ-ch2",type:"note",subtopic:"President, PM, and Council of Ministers",content:'THE PRESIDENT: Head of State (ceremonial), Supreme Commander of Armed Forces, elected by an Electoral College (MPs + MLAs), term of 5 years, can be re-elected. Powers: appoints PM, governors, judges; can declare Emergency.\nTHE PRIME MINISTER: Head of Government (real executive power), leader of majority party in Lok Sabha, heads the Council of Ministers, advises the President.\nCOUNCIL OF MINISTERS: Cabinet Ministers (important portfolios), Ministers of State, Deputy Ministers. Collectively responsible to Lok Sabha.',explanation:'The President is like a ceremonial head (signs documents, represents India), while the PM actually runs the government and makes decisions. The President acts on PM\'s advice.',teacherTip:'President = Head of State (nominal). PM = Head of Government (real power). Like a company: President = Chairman, PM = CEO.',examTip:'Know the difference between nominal and real executive clearly.'},
// T/F
{id:"cv2tf1",topicId:"civ-ch2",type:"true_false",subtopic:"Objective Questions",question:"The President of India is directly elected by the people.",correctAnswer:"false",answer:"False. The President is elected INDIRECTLY by an Electoral College consisting of elected members of Parliament (Lok Sabha + Rajya Sabha) and elected members of State Legislative Assemblies.",teacherTip:'Only Lok Sabha MPs are directly elected by people. President is elected by elected representatives.',examTip:'Name the members of the Electoral College for the Presidential election.'},
// Short answer
{id:"cv2sa1",topicId:"civ-ch2",type:"short_answer",subtopic:"Short/Long Answer",question:"Distinguish between the powers of the President and the Prime Minister.",answer:'PRESIDENT (Head of State — Nominal Executive):\n• Ceremonial head of India\n• Supreme Commander of Armed Forces\n• Appoints PM, Governors, Judges, Ambassadors\n• Can declare National Emergency, State Emergency, Financial Emergency\n• Gives assent to bills to make them laws\n• Acts on the advice of the PM and Council of Ministers\n\nPRIME MINISTER (Head of Government — Real Executive):\n• Heads the Council of Ministers\n• Makes all major policy decisions\n• Leader of the majority party in Lok Sabha\n• Advises the President on all appointments\n• Coordinates between different ministries\n• Represents India in international summits\n• Can recommend dissolution of Lok Sabha\n\nKey difference: The President has more powers ON PAPER, but the PM exercises REAL power in practice.',teacherTip:'The President acts, the PM decides. The President signs, the PM governs.',examTip:'Use "nominal" for President and "real" for PM when comparing executive powers.'},

// ====== C-CH3: THE JUDICIARY ======
{id:"cv3n1",topicId:"civ-ch3",type:"note",subtopic:"Indian Judiciary",content:'India has an INDEPENDENT, INTEGRATED judicial system:\n(1) SUPREME COURT — highest court, New Delhi, headed by Chief Justice of India (CJI). Hears appeals, protects Fundamental Rights, settles disputes between Centre and states. Has power of JUDICIAL REVIEW (can strike down unconstitutional laws).\n(2) HIGH COURTS — one for each state (or shared), headed by Chief Justice of the High Court.\n(3) DISTRICT/SUBORDINATE COURTS — at district level, handle local cases.\nJudges are appointed by the President (on collegium\'s recommendation), ensuring independence from government.',explanation:'The judiciary is the guardian of the Constitution. It ensures that no law violates citizens\' fundamental rights and no government acts beyond its power.',teacherTip:'Supreme Court = Guardian of the Constitution. Judicial Review = its most powerful weapon.',examTip:'Know: Structure (3 levels), Judicial Review (power to check laws), Independence (how judges are appointed).'},
// T/F
{id:"cv3tf1",topicId:"civ-ch3",type:"true_false",subtopic:"Objective Questions",question:"The Supreme Court can declare a law unconstitutional.",correctAnswer:"true",answer:"True. This power is called JUDICIAL REVIEW. The Supreme Court can examine any law passed by Parliament or State Legislature and declare it unconstitutional (null and void) if it violates the Constitution.",teacherTip:'Judicial Review = the judiciary\'s power to check the legislature. Essential for democracy!',examTip:'Define Judicial Review and explain why it\'s important for protecting citizens\' rights.'},
// Short answer
{id:"cv3sa1",topicId:"civ-ch3",type:"short_answer",subtopic:"Short/Long Answer",question:"What is Judicial Review? Why is it important?",answer:'JUDICIAL REVIEW is the power of the Supreme Court (and High Courts) to examine any law passed by Parliament or State Legislatures and declare it unconstitutional (null and void) if it violates the fundamental rights or other provisions of the Constitution.\n\nIMPORTANCE:\n1. PROTECTS FUNDAMENTAL RIGHTS: Ensures no law takes away citizens\' basic rights guaranteed by the Constitution\n2. MAINTAINS SUPREMACY OF CONSTITUTION: The Constitution is the supreme law; no government can override it\n3. CHECKS & BALANCES: Prevents the Legislature from passing arbitrary or unjust laws\n4. FEDERAL BALANCE: Settles disputes between Central and State governments\n5. RULE OF LAW: Ensures that even the government must follow the law\n\nJudicial Review makes the Supreme Court the "Guardian of the Constitution."',teacherTip:'Without Judicial Review, the government could pass any law, even unfair ones. JR is the safety net!',examTip:'Define the term, give 3+ reasons for its importance, and call the SC the "Guardian of the Constitution."'},

// ====== C-CH4: THE UNITED NATIONS ======
{id:"cv4n1",topicId:"civ-ch4",type:"note",subtopic:"United Nations Organization",content:'The UNITED NATIONS (UN) was established on October 24, 1945 after World War II to maintain international peace and security. Headquarters: New York. Currently 193 member states. Main organs:\n(1) GENERAL ASSEMBLY — all members, each has 1 vote, discusses global issues\n(2) SECURITY COUNCIL — 15 members (5 permanent: USA, UK, France, Russia, China with VETO power + 10 non-permanent for 2-year terms)\n(3) SECRETARIAT — headed by Secretary-General (administrative body)\n(4) INTERNATIONAL COURT OF JUSTICE (ICJ) — settles legal disputes between nations, The Hague\n(5) ECONOMIC AND SOCIAL COUNCIL (ECOSOC)\nAgencies: WHO, UNESCO, UNICEF, ILO.',explanation:'After two devastating World Wars, nations decided they needed a global organization where they could talk instead of fight. The UN is that platform.',teacherTip:'5 Permanent members = P5 = USA, UK, France, Russia, China. They have VETO power (can block any decision).',examTip:'Know all 6 organs, the 5 permanent members, and at least 4 UN agencies with their full forms.'},
// T/F
{id:"cv4tf1",topicId:"civ-ch4",type:"true_false",subtopic:"Objective Questions",question:"India is a permanent member of the UN Security Council.",correctAnswer:"false",answer:"False. India is NOT a permanent member. The 5 permanent members are: USA, UK, France, Russia, and China. India has been a non-permanent member several times and is campaigning for permanent membership.",teacherTip:'P5 = USA, UK, France, Russia, China. India wants to join but hasn\'t yet.',examTip:'Name all 5 permanent members and explain what "veto power" means.'},
// Fill blank
{id:"cv4fb1",topicId:"civ-ch4",type:"fill_blank",subtopic:"Objective Questions",question:"The United Nations was established on October 24, ______.",blankAnswer:"1945",answer:"The UN was established on October 24, 1945, after World War II ended. This date is celebrated as United Nations Day.",teacherTip:'1945 = end of WWII = birth of UN. The two events are directly connected.',examTip:'Also know that the UN Charter was signed in San Francisco in June 1945.'},
// MCQ
{id:"cv4mcq1",topicId:"civ-ch4",type:"mcq",subtopic:"Objective Questions",question:"The headquarters of the United Nations is in:",options:["Geneva","London","New York","Paris"],correctOption:2,answer:"The UN headquarters is in New York City, USA. However, other UN offices are in Geneva (Switzerland), Vienna (Austria), and Nairobi (Kenya).",teacherTip:'UN HQ = New York. ICJ = The Hague (Netherlands). WHO = Geneva.',examTip:'Know the locations of at least 3 UN organs/agencies.'},
// Short answer
{id:"cv4sa1",topicId:"civ-ch4",type:"short_answer",subtopic:"Short/Long Answer",question:"What are the main objectives of the United Nations? Name its principal organs.",answer:'OBJECTIVES OF THE UN:\n1. Maintain international peace and security\n2. Develop friendly relations among nations based on equality\n3. Promote international cooperation to solve economic, social, cultural, and humanitarian problems\n4. Protect human rights and fundamental freedoms for all people\n5. Serve as a centre for harmonizing the actions of nations\n\nPRINCIPAL ORGANS (6):\n1. GENERAL ASSEMBLY — "Parliament of the world," all 193 members, one vote each\n2. SECURITY COUNCIL — 15 members (5 permanent with veto), maintains peace\n3. ECONOMIC AND SOCIAL COUNCIL (ECOSOC) — coordinates economic and social work\n4. TRUSTEESHIP COUNCIL — supervised trust territories (now suspended)\n5. INTERNATIONAL COURT OF JUSTICE (ICJ) — settles legal disputes, The Hague\n6. SECRETARIAT — administrative body headed by Secretary-General',teacherTip:'The UN has 6 organs but the most powerful is the Security Council because of veto power.',examTip:'List all 6 organs with one-line descriptions and name the 5 permanent Security Council members.'},
];
